TRACKING DATA DAN CEK KOLOM

In [ ]:
import pandas as pd

tracking_path = r"C:\VAEP-Track\data\sportec_idsse\J03WPY_tracking.csv"

tracking = pd.read_csv(tracking_path)

print("Shape:", tracking.shape)
display(tracking.head())

print(tracking.columns.tolist())
print(tracking.info())

Shape: (146211, 133)

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,DFL-OBJ-0000NZ_x,...,DFL-OBJ-002GM1_d,DFL-OBJ-002GM1_s,DFL-OBJ-J01K2L_x,DFL-OBJ-J01K2L_y,DFL-OBJ-J01K2L_d,DFL-OBJ-J01K2L_s,DFL-OBJ-0001BX_x,DFL-OBJ-0001BX_y,DFL-OBJ-0001BX_d,DFL-OBJ-0001BX_s
0,1,0 days 00:00:00,10000,alive,DFL-CLU-00000P,0.560952,0.500588,0.15,60.77,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0 days 00:00:00.040000,10001,alive,DFL-CLU-00000P,0.566571,0.500294,0.18,59.15,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0 days 00:00:00.080000,10002,alive,DFL-CLU-00000P,0.572381,0.500147,0.21,54.09,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0 days 00:00:00.120000,10003,alive,DFL-CLU-00000P,0.578095,0.499559,0.25,53.68,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0 days 00:00:00.160000,10004,alive,DFL-CLU-00000P,0.583429,0.499265,0.24,53.90,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['period_id', 'timestamp', 'frame_id', 'ball_state', 'ball_owning_team_id', 'ball_x', 'ball_y', 'ball_z', 'ball_speed', 'DFL-OBJ-0000NZ_x', 'DFL-OBJ-0000NZ_y', 'DFL-OBJ-0000NZ_d', 'DFL-OBJ-0000NZ_s', 'DFL-OBJ-0000F8_x', 'DFL-OBJ-0000F8_y', 'DFL-OBJ-0000F8_d', 'DFL-OBJ-0000F8_s', 'DFL-OBJ-00028V_x', 'DFL-OBJ-00028V_y', 'DFL-OBJ-00028V_d', 'DFL-OBJ-00028V_s', 'DFL-OBJ-002FXT_x', 'DFL-OBJ-002FXT_y', 'DFL-OBJ-002FXT_d', 'DFL-OBJ-002FXT_s', 'DFL-OBJ-0026RH_x', 'DFL-OBJ-0026RH_y', 'DFL-OBJ-0026RH_d', 'DFL-OBJ-0026RH_s', 'DFL-OBJ-0028FW_x', 'DFL-OBJ-0028FW_y', 'DFL-OBJ-0028FW_d', 'DFL-OBJ-0028FW_s', 'DFL-OBJ-002G5J_x', 'DFL-OBJ-002G5J_y', 'DFL-OBJ-002G5J_d', 'DFL-OBJ-002G5J_s', 'DFL-OBJ-002GMO_x', 'DFL-OBJ-002GMO_y', 'DFL-OBJ-002GMO_d', 'DFL-OBJ-002GMO_s', 'DFL-OBJ-002GM9_x', 'DFL-OBJ-002GM9_y', 'DFL-OBJ-002GM9_d', 'DFL-OBJ-002GM9_s', 'DFL-OBJ-J01H9X_x', 'DFL-OBJ-J01H9X_y', 'DFL-OBJ-J01H9X_d', 'DFL-OBJ-J01H9X_s', 'DFL-OBJ-J01KJ5_x', 'DFL-OBJ-J01KJ5_y', 'DFL-OBJ-J01KJ5_d', 'DFL-OBJ-J01KJ5_s', 'DFL-OBJ-00008F_x', 'DFL-OBJ-00008F_y', 'DFL-OBJ-00008F_d', 'DFL-OBJ-00008F_s', 'DFL-OBJ-0000EJ_x', 'DFL-OBJ-0000EJ_y', 'DFL-OBJ-0000EJ_d', 'DFL-OBJ-0000EJ_s', 'DFL-OBJ-0001HW_x', 'DFL-OBJ-0001HW_y', 'DFL-OBJ-0001HW_d', 'DFL-OBJ-0001HW_s', 'DFL-OBJ-0001LJ_x', 'DFL-OBJ-0001LJ_y', 'DFL-OBJ-0001LJ_d', 'DFL-OBJ-0001LJ_s', 'DFL-OBJ-002595_x', 'DFL-OBJ-002595_y', 'DFL-OBJ-002595_d', 'DFL-OBJ-002595_s', 'DFL-OBJ-J0178P_x', 'DFL-OBJ-J0178P_y', 'DFL-OBJ-J0178P_d', 'DFL-OBJ-J0178P_s', 'DFL-OBJ-0028BZ_x', 'DFL-OBJ-0028BZ_y', 'DFL-OBJ-0028BZ_d', 'DFL-OBJ-0028BZ_s', 'DFL-OBJ-0028T3_x', 'DFL-OBJ-0028T3_y', 'DFL-OBJ-0028T3_d', 'DFL-OBJ-0028T3_s', 'DFL-OBJ-002G68_x', 'DFL-OBJ-002G68_y', 'DFL-OBJ-002G68_d', 'DFL-OBJ-002G68_s', 'DFL-OBJ-002FYC_x', 'DFL-OBJ-002FYC_y', 'DFL-OBJ-002FYC_d', 'DFL-OBJ-002FYC_s', 'DFL-OBJ-002GG4_x', 'DFL-OBJ-002GG4_y', 'DFL-OBJ-002GG4_d', 'DFL-OBJ-002GG4_s', 'DFL-OBJ-J01CP5_x', 'DFL-OBJ-J01CP5_y', 'DFL-OBJ-J01CP5_d', 'DFL-OBJ-J01CP5_s', 'DFL-OBJ-J01NQ8_x', 'DFL-OBJ-J01NQ8_y', 'DFL-OBJ-J01NQ8_d', 'DFL-OBJ-J01NQ8_s', 'DFL-OBJ-00008K_x', 'DFL-OBJ-00008K_y', 'DFL-OBJ-00008K_d', 'DFL-OBJ-00008K_s', 'DFL-OBJ-0026IA_x', 'DFL-OBJ-0026IA_y', 'DFL-OBJ-0026IA_d', 'DFL-OBJ-0026IA_s', 'DFL-OBJ-002G78_x', 'DFL-OBJ-002G78_y', 'DFL-OBJ-002G78_d', 'DFL-OBJ-002G78_s', 'DFL-OBJ-00286U_x', 'DFL-OBJ-00286U_y', 'DFL-OBJ-00286U_d', 'DFL-OBJ-00286U_s', 'DFL-OBJ-002GM1_x', 'DFL-OBJ-002GM1_y', 'DFL-OBJ-002GM1_d', 'DFL-OBJ-002GM1_s', 'DFL-OBJ-J01K2L_x', 'DFL-OBJ-J01K2L_y', 'DFL-OBJ-J01K2L_d', 'DFL-OBJ-J01K2L_s', 'DFL-OBJ-0001BX_x', 'DFL-OBJ-0001BX_y', 'DFL-OBJ-0001BX_d', 'DFL-OBJ-0001BX_s']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146211 entries, 0 to 146210
Columns: 133 entries, period_id to DFL-OBJ-0001BX_s
dtypes: float64(128), int64(2), object(3)
memory usage: 148.4+ MB
None

In [ ]:
events_path = r"C:\VAEP-Track\data\sportec_idsse\J03WPY_events.csv"

events = pd.read_csv(events_path)

print("Shape:", events.shape)
display(events.head())

print(events.columns.tolist())
events.info()

Shape: (1572, 19)

,event_id,event_type,period_id,timestamp,end_timestamp,ball_state,ball_owning_team,team_id,player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,receiver_player_id,set_piece_type,result,success,body_part_type,card_type
0,18237400000006,PASS,1,0 days 00:00:00,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002G5J,0.500000,0.500000,0.733810,0.485294,DFL-OBJ-0028FW,KICK_OFF,COMPLETE,True,NaN,NaN
1,18237400000007,PASS,1,0 days 00:00:01.697000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-0028FW,0.718476,0.486765,0.335905,0.913382,DFL-OBJ-002FXT,NaN,COMPLETE,True,NaN,NaN
2,18237400000008,GENERIC:TacklingGame,1,0 days 00:00:04.936000,NaN,alive,NaN,NaN,NaN,0.335905,0.913382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18237400000009,PASS,1,0 days 00:00:06.465000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002FXT,0.295810,0.923235,NaN,NaN,NaN,NaN,INCOMPLETE,False,NaN,NaN
4,18237400000010,PASS,1,0 days 00:00:11.553000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0001HW,0.084000,0.680000,0.145048,0.240441,DFL-OBJ-002G68,NaN,COMPLETE,True,NaN,NaN

['event_id', 'event_type', 'period_id', 'timestamp', 'end_timestamp', 'ball_state', 'ball_owning_team', 'team_id', 'player_id', 'coordinates_x', 'coordinates_y', 'end_coordinates_x', 'end_coordinates_y', 'receiver_player_id', 'set_piece_type', 'result', 'success', 'body_part_type', 'card_type']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1572 entries, 0 to 1571
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id            1572 non-null   object
 1   event_type          1572 non-null   object
 2   period_id           1572 non-null   int64
 3   timestamp           1572 non-null   object
 4   end_timestamp       0 non-null      float64
 5   ball_state          1572 non-null   object
 6   ball_owning_team    0 non-null      float64
 7   team_id             1280 non-null   object
 8   player_id           1278 non-null   object
 9   coordinates_x       1392 non-null   float64
 10  coordinates_y       1392 non-null   float64
 11  end_coordinates_x   699 non-null    float64
 12  end_coordinates_y   699 non-null    float64
 13  receiver_player_id  723 non-null    object
 14  set_piece_type      93 non-null     object
 15  result              916 non-null    object
 16  success             916 non-null    object
 17  body_part_type      26 non-null     object
 18  card_type           9 non-null      object
dtypes: float64(6), int64(1), object(12)
memory usage: 233.5+ KB

In [ ]:
display(events.head())
display(tracking.head())

,event_id,event_type,period_id,timestamp,end_timestamp,ball_state,ball_owning_team,team_id,player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,receiver_player_id,set_piece_type,result,success,body_part_type,card_type
0,18237400000006,PASS,1,0 days 00:00:00,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002G5J,0.500000,0.500000,0.733810,0.485294,DFL-OBJ-0028FW,KICK_OFF,COMPLETE,True,NaN,NaN
1,18237400000007,PASS,1,0 days 00:00:01.697000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-0028FW,0.718476,0.486765,0.335905,0.913382,DFL-OBJ-002FXT,NaN,COMPLETE,True,NaN,NaN
2,18237400000008,GENERIC:TacklingGame,1,0 days 00:00:04.936000,NaN,alive,NaN,NaN,NaN,0.335905,0.913382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18237400000009,PASS,1,0 days 00:00:06.465000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002FXT,0.295810,0.923235,NaN,NaN,NaN,NaN,INCOMPLETE,False,NaN,NaN
4,18237400000010,PASS,1,0 days 00:00:11.553000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0001HW,0.084000,0.680000,0.145048,0.240441,DFL-OBJ-002G68,NaN,COMPLETE,True,NaN,NaN

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,DFL-OBJ-0000NZ_x,...,DFL-OBJ-002GM1_d,DFL-OBJ-002GM1_s,DFL-OBJ-J01K2L_x,DFL-OBJ-J01K2L_y,DFL-OBJ-J01K2L_d,DFL-OBJ-J01K2L_s,DFL-OBJ-0001BX_x,DFL-OBJ-0001BX_y,DFL-OBJ-0001BX_d,DFL-OBJ-0001BX_s
0,1,0 days 00:00:00,10000,alive,DFL-CLU-00000P,0.560952,0.500588,0.15,60.77,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0 days 00:00:00.040000,10001,alive,DFL-CLU-00000P,0.566571,0.500294,0.18,59.15,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,0 days 00:00:00.080000,10002,alive,DFL-CLU-00000P,0.572381,0.500147,0.21,54.09,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,0 days 00:00:00.120000,10003,alive,DFL-CLU-00000P,0.578095,0.499559,0.25,53.68,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,0 days 00:00:00.160000,10004,alive,DFL-CLU-00000P,0.583429,0.499265,0.24,53.90,0.505429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
events["ball_owning_team"].value_counts(dropna=False)
events["team_id"].value_counts(dropna=False)

team_id
DFL-CLU-00000P    785
DFL-CLU-000005    495
NaN               292
Name: count, dtype: int64

In [ ]:
events["event_type"].value_counts()
print(events["event_type"].unique())

['PASS' 'GENERIC:TacklingGame' 'GENERIC:OtherBallAction' 'GENERIC:Delete'
 'BALL_OUT' 'FOUL_COMMITTED' 'SHOT' 'CARD' 'GENERIC:FairPlay'
 'GENERIC:Offside' 'SUBSTITUTION' 'GENERIC:SpectacularPlay'
 'GENERIC:PenaltyNotAwarded' 'GENERIC:Run'
 'GENERIC:PossessionLossBeforeGoal' 'GENERIC:Nutmeg' 'GENERIC:RefereeBall'
 'GENERIC:BallDeflection' 'RECOVERY']

In [ ]:
events[["timestamp", "event_type", "team_id", "player_id", "success"]].head(100)

,timestamp,event_type,team_id,player_id,success
0,0 days 00:00:00,PASS,DFL-CLU-00000P,DFL-OBJ-002G5J,True
1,0 days 00:00:01.697000,PASS,DFL-CLU-00000P,DFL-OBJ-0028FW,True
2,0 days 00:00:04.936000,GENERIC:TacklingGame,NaN,NaN,NaN
3,0 days 00:00:06.465000,PASS,DFL-CLU-00000P,DFL-OBJ-002FXT,False
4,0 days 00:00:11.553000,PASS,DFL-CLU-000005,DFL-OBJ-0001HW,True
...,...,...,...,...,...
95,0 days 00:04:25.394000,PASS,DFL-CLU-00000P,DFL-OBJ-002GMO,True
96,0 days 00:04:28.418000,PASS,DFL-CLU-00000P,DFL-OBJ-J01H9X,True
97,0 days 00:04:29.338000,GENERIC:OtherBallAction,DFL-CLU-00000P,DFL-OBJ-002GM9,NaN
98,0 days 00:04:31.083000,GENERIC:TacklingGame,NaN,NaN,NaN
99,0 days 00:04:34.211000,GENERIC:TacklingGame,NaN,NaN,NaN

In [ ]:
events["prev_team_id"] = events["team_id"].shift(1)

changes = events[
    events["team_id"].notna() &
    events["prev_team_id"].notna() &
    (events["team_id"] != events["prev_team_id"])
]

display(
    changes[
        [
            "timestamp",
            "event_type",
            "team_id",
            "prev_team_id",
            "player_id",
            "success"
        ]
    ].head(30)
)

,timestamp,event_type,team_id,prev_team_id,player_id,success
4,0 days 00:00:11.553000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-0001HW,True
25,0 days 00:01:06.915000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002GG4,True
40,0 days 00:01:58.329000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-00028V,True
45,0 days 00:01:21.130000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002FYC,True
46,0 days 00:02:16.450000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002GMO,True
50,0 days 00:01:21.330000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002595,True
62,0 days 00:02:53.658000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-0028BZ,True
65,0 days 00:03:03.442000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002GM9,True
73,0 days 00:03:29.738000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002FYC,True
77,0 days 00:03:38.937000,GENERIC:OtherBallAction,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002GMO,NaN
79,0 days 00:03:52.034000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002FYC,True
83,0 days 00:03:59.506000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002GM9,True
101,0 days 00:05:10.299000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002G5J,True
102,0 days 00:03:57.890000,GENERIC:OtherBallAction,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-J0178P,NaN
108,0 days 00:05:50.643000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002G5J,False
124,0 days 00:08:01.949000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-0028FW,True
134,0 days 00:08:30.820000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-00008F,True
136,0 days 00:08:33.220000,GENERIC:OtherBallAction,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002GM9,NaN
139,0 days 00:08:52.454000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002FYC,True
144,0 days 00:09:08.820000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-0000NZ,True
158,0 days 00:09:47.208000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-J01H9X,True
176,0 days 00:10:27.541000,GENERIC:OtherBallAction,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002G68,NaN
184,0 days 00:11:12.838000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002G5J,False
191,0 days 00:11:34.542000,GENERIC:OtherBallAction,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-J01KJ5,NaN
192,0 days 00:11:40.030000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002GG4,True
196,0 days 00:11:45.223000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-J01H9X,True
211,0 days 00:12:28.230000,GENERIC:OtherBallAction,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002G68,NaN
220,0 days 00:12:51.991000,PASS,DFL-CLU-00000P,DFL-CLU-000005,DFL-OBJ-002GM9,True
236,0 days 00:13:27.366000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-002GG4,True
240,0 days 00:13:35.511000,PASS,DFL-CLU-000005,DFL-CLU-00000P,DFL-OBJ-00008F,True

: