DAFTAR EVENTS

In [19]:
import pandas as pd

events_path = r"C:\VAEP-Track\data\sportec_idsse\J03WPY_events.csv"
events = pd.read_csv(events_path)
events["timestamp"] = pd.to_timedelta(events["timestamp"])

print("Shape:", events.shape)
display(events.head())

Shape: (1572, 19)

,event_id,event_type,period_id,timestamp,end_timestamp,ball_state,ball_owning_team,team_id,player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,receiver_player_id,set_piece_type,result,success,body_part_type,card_type
0,18237400000006,PASS,1,0 days 00:00:00,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002G5J,0.500000,0.500000,0.733810,0.485294,DFL-OBJ-0028FW,KICK_OFF,COMPLETE,True,NaN,NaN
1,18237400000007,PASS,1,0 days 00:00:01.697000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-0028FW,0.718476,0.486765,0.335905,0.913382,DFL-OBJ-002FXT,NaN,COMPLETE,True,NaN,NaN
2,18237400000008,GENERIC:TacklingGame,1,0 days 00:00:04.936000,NaN,alive,NaN,NaN,NaN,0.335905,0.913382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18237400000009,PASS,1,0 days 00:00:06.465000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002FXT,0.295810,0.923235,NaN,NaN,NaN,NaN,INCOMPLETE,False,NaN,NaN
4,18237400000010,PASS,1,0 days 00:00:11.553000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0001HW,0.084000,0.680000,0.145048,0.240441,DFL-OBJ-002G68,NaN,COMPLETE,True,NaN,NaN

In [20]:
events["event_type"].value_counts()

event_type
PASS                                891
GENERIC:OtherBallAction             252
GENERIC:TacklingGame                208
BALL_OUT                             70
GENERIC:Delete                       60
SHOT                                 26
FOUL_COMMITTED                       18
RECOVERY                             12
CARD                                  9
SUBSTITUTION                          9
GENERIC:RefereeBall                   4
GENERIC:Offside                       2
GENERIC:FairPlay                      2
GENERIC:SpectacularPlay               2
GENERIC:PenaltyNotAwarded             2
GENERIC:Nutmeg                        2
GENERIC:Run                           1
GENERIC:PossessionLossBeforeGoal      1
GENERIC:BallDeflection                1
Name: count, dtype: int64

In [21]:
events["team_id"].value_counts(dropna=False)

team_id
DFL-CLU-00000P    785
DFL-CLU-000005    495
NaN               292
Name: count, dtype: int64

In [22]:
events["ball_owning_team"].value_counts(dropna=False)

ball_owning_team
NaN    1572
Name: count, dtype: int64

In [23]:
display(
    events[
        [
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "receiver_player_id",
            "coordinates_x",
            "coordinates_y",
            "end_coordinates_x",
            "end_coordinates_y",
            "success"
        ]
    ].head(100)
)

,timestamp,event_type,team_id,player_id,receiver_player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,success
0,0 days 00:00:00,PASS,DFL-CLU-00000P,DFL-OBJ-002G5J,DFL-OBJ-0028FW,0.500000,0.500000,0.733810,0.485294,True
1,0 days 00:00:01.697000,PASS,DFL-CLU-00000P,DFL-OBJ-0028FW,DFL-OBJ-002FXT,0.718476,0.486765,0.335905,0.913382,True
2,0 days 00:00:04.936000,GENERIC:TacklingGame,NaN,NaN,NaN,0.335905,0.913382,NaN,NaN,NaN
3,0 days 00:00:06.465000,PASS,DFL-CLU-00000P,DFL-OBJ-002FXT,NaN,0.295810,0.923235,NaN,NaN,False
4,0 days 00:00:11.553000,PASS,DFL-CLU-000005,DFL-OBJ-0001HW,DFL-OBJ-002G68,0.084000,0.680000,0.145048,0.240441,True
...,...,...,...,...,...,...,...,...,...,...
95,0 days 00:04:25.394000,PASS,DFL-CLU-00000P,DFL-OBJ-002GMO,DFL-OBJ-J01H9X,0.601143,0.053088,0.645048,0.421765,True
96,0 days 00:04:28.418000,PASS,DFL-CLU-00000P,DFL-OBJ-J01H9X,DFL-OBJ-002GM9,0.645048,0.421765,0.545810,0.834853,True
97,0 days 00:04:29.338000,GENERIC:OtherBallAction,DFL-CLU-00000P,DFL-OBJ-002GM9,NaN,0.319619,0.890882,NaN,NaN,NaN
98,0 days 00:04:31.083000,GENERIC:TacklingGame,NaN,NaN,NaN,0.432952,0.898676,NaN,NaN,NaN
99,0 days 00:04:34.211000,GENERIC:TacklingGame,NaN,NaN,NaN,0.320667,0.916324,NaN,NaN,NaN

RECOVERY

In [24]:
recovery = events[events["event_type"] == "RECOVERY"]

display(recovery)
print(recovery.columns.tolist())

,event_id,event_type,period_id,timestamp,end_timestamp,ball_state,ball_owning_team,team_id,player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,receiver_player_id,set_piece_type,result,success,body_part_type,card_type
1560,18237403500029,RECOVERY,2,-1 days +22:59:06.214000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-002GG4,0.487619,0.873088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,18237403500484,RECOVERY,2,-1 days +23:26:28.192000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002GMO,0.758571,0.578235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,18237403500488,RECOVERY,2,-1 days +23:26:40.856000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-002G68,0.249048,0.277353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1563,18237403500517,RECOVERY,2,-1 days +23:28:18.865000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0028T3,0.663143,0.951324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564,18237403500523,RECOVERY,2,-1 days +23:28:50.473000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-002FYC,0.646000,0.497059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1565,18237403500940,RECOVERY,2,0 days 00:12:33.775000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-002G68,0.756667,0.803824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1566,18237403500986,RECOVERY,2,0 days 00:16:24.192000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-0000F8,0.676571,0.737500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1567,18237403501054,RECOVERY,2,0 days 00:22:21.539000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-J01KJ5,0.188952,0.241912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1568,18237403501282,RECOVERY,2,0 days 00:40:21.596000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0026IA,0.862571,0.822941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1569,18237403501368,RECOVERY,2,0 days 00:45:13.598000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0001HW,0.966571,0.471912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1570,18237403501417,RECOVERY,2,0 days 00:48:27.624000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-0028FW,0.042000,0.492647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1571,18237403501456,RECOVERY,2,0 days 00:45:39.494000,NaN,alive,NaN,DFL-CLU-000005,DFL-OBJ-0028T3,0.699429,0.243382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['event_id', 'event_type', 'period_id', 'timestamp', 'end_timestamp', 'ball_state', 'ball_owning_team', 'team_id', 'player_id', 'coordinates_x', 'coordinates_y', 'end_coordinates_x', 'end_coordinates_y', 'receiver_player_id', 'set_piece_type', 'result', 'success', 'body_part_type', 'card_type']

In [25]:
display(
    recovery[
        [
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "ball_owning_team",
            "coordinates_x",
            "coordinates_y",
            "success"
        ]
    ]
)

,timestamp,event_type,team_id,player_id,ball_owning_team,coordinates_x,coordinates_y,success
1560,-1 days +22:59:06.214000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002GG4,NaN,0.487619,0.873088,NaN
1561,-1 days +23:26:28.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-002GMO,NaN,0.758571,0.578235,NaN
1562,-1 days +23:26:40.856000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,NaN,0.249048,0.277353,NaN
1563,-1 days +23:28:18.865000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,NaN,0.663143,0.951324,NaN
1564,-1 days +23:28:50.473000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002FYC,NaN,0.646000,0.497059,NaN
1565,0 days 00:12:33.775000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,NaN,0.756667,0.803824,NaN
1566,0 days 00:16:24.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0000F8,NaN,0.676571,0.737500,NaN
1567,0 days 00:22:21.539000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-J01KJ5,NaN,0.188952,0.241912,NaN
1568,0 days 00:40:21.596000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0026IA,NaN,0.862571,0.822941,NaN
1569,0 days 00:45:13.598000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0001HW,NaN,0.966571,0.471912,NaN
1570,0 days 00:48:27.624000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0028FW,NaN,0.042000,0.492647,NaN
1571,0 days 00:45:39.494000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,NaN,0.699429,0.243382,NaN

Kita ingin melihat bagaimana event RECOVERY sebenarnya dicatat oleh IDSSE.

In [26]:
tackles = events[
    events["event_type"] == "GENERIC:TacklingGame"
]

display(
    tackles[
        [
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "ball_owning_team",
            "coordinates_x",
            "coordinates_y",
            "success"
        ]
    ].head(30)
)

,timestamp,event_type,team_id,player_id,ball_owning_team,coordinates_x,coordinates_y,success
2,0 days 00:00:04.936000,GENERIC:TacklingGame,NaN,NaN,NaN,0.335905,0.913382,NaN
8,0 days 00:00:24.490000,GENERIC:TacklingGame,NaN,NaN,NaN,0.552762,0.162941,NaN
12,0 days 00:00:31.090000,GENERIC:TacklingGame,NaN,NaN,NaN,0.432952,0.320147,NaN
16,0 days 00:00:26.490000,GENERIC:TacklingGame,NaN,NaN,NaN,0.464286,0.182059,NaN
22,0 days 00:00:28.890000,GENERIC:TacklingGame,NaN,NaN,NaN,0.533810,0.154118,NaN
29,0 days 00:00:30.730000,GENERIC:TacklingGame,NaN,NaN,NaN,0.450952,0.331912,NaN
34,0 days 00:01:28.841000,GENERIC:TacklingGame,NaN,NaN,NaN,0.901048,0.540441,NaN
37,0 days 00:00:32.530000,GENERIC:TacklingGame,NaN,NaN,NaN,0.410095,0.267206,NaN
38,0 days 00:01:35.937000,GENERIC:TacklingGame,NaN,NaN,NaN,0.621333,0.455147,NaN
51,0 days 00:01:07.410000,GENERIC:TacklingGame,NaN,NaN,NaN,0.742190,0.625588,NaN
54,0 days 00:01:08.930000,GENERIC:TacklingGame,NaN,NaN,NaN,0.749810,0.615294,NaN
84,0 days 00:03:58.562000,GENERIC:TacklingGame,NaN,NaN,NaN,0.786857,0.295147,NaN
86,0 days 00:04:02.066000,GENERIC:TacklingGame,NaN,NaN,NaN,0.564190,0.133676,NaN
88,0 days 00:03:54.130000,GENERIC:TacklingGame,NaN,NaN,NaN,0.643238,0.052794,NaN
89,0 days 00:04:03.434000,GENERIC:TacklingGame,NaN,NaN,NaN,0.613714,0.364118,NaN
98,0 days 00:04:31.083000,GENERIC:TacklingGame,NaN,NaN,NaN,0.432952,0.898676,NaN
99,0 days 00:04:34.211000,GENERIC:TacklingGame,NaN,NaN,NaN,0.320667,0.916324,NaN
103,0 days 00:05:11.660000,GENERIC:TacklingGame,NaN,NaN,NaN,0.078000,0.323088,NaN
105,0 days 00:05:14.597000,GENERIC:TacklingGame,NaN,NaN,NaN,0.043810,0.463971,NaN
111,0 days 00:05:55.730000,GENERIC:TacklingGame,NaN,NaN,NaN,0.175048,0.443529,NaN
125,0 days 00:07:42.610000,GENERIC:TacklingGame,NaN,NaN,NaN,0.959048,0.425882,NaN
131,0 days 00:08:23.725000,GENERIC:TacklingGame,NaN,NaN,NaN,0.223619,0.261324,NaN
150,0 days 00:09:07.450000,GENERIC:TacklingGame,NaN,NaN,NaN,0.467143,0.232059,NaN
154,0 days 00:09:34.928000,GENERIC:TacklingGame,NaN,NaN,NaN,0.510000,0.023529,NaN
174,0 days 00:10:23.452000,GENERIC:TacklingGame,NaN,NaN,NaN,0.363429,0.029412,NaN
182,0 days 00:10:41.101000,GENERIC:TacklingGame,NaN,NaN,NaN,0.325429,0.302500,NaN
185,0 days 00:11:13.470000,GENERIC:TacklingGame,NaN,NaN,NaN,0.140857,0.480147,NaN
193,0 days 00:11:39.238000,GENERIC:TacklingGame,NaN,NaN,NaN,0.559429,0.870735,NaN
208,0 days 00:12:19.990000,GENERIC:TacklingGame,NaN,NaN,NaN,0.322571,0.834118,NaN
214,0 days 00:12:28.410000,GENERIC:TacklingGame,NaN,NaN,NaN,0.324476,0.810588,NaN

RINCIAN TACKLING GAME (EVENTS)

POSSESION BEFORE GOAL

In [27]:
loss_goal = events[
    events["event_type"] == "GENERIC:PossessionLossBeforeGoal"
]

display(loss_goal)

,event_id,event_type,period_id,timestamp,end_timestamp,ball_state,ball_owning_team,team_id,player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,receiver_player_id,set_piece_type,result,success,body_part_type,card_type
1549,18237400001489,GENERIC:PossessionLossBeforeGoal,2,0 days 00:01:19.350000,NaN,alive,NaN,DFL-CLU-00000P,DFL-OBJ-002GMO,0.254952,0.597647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
display(
    events[
        [
            "timestamp",
            "event_type",
            "team_id",
            "ball_owning_team",
            "player_id",
            "receiver_player_id",
            "success"
        ]
    ].head(50)
)

,timestamp,event_type,team_id,ball_owning_team,player_id,receiver_player_id,success
0,0 days 00:00:00,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002G5J,DFL-OBJ-0028FW,True
1,0 days 00:00:01.697000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0028FW,DFL-OBJ-002FXT,True
2,0 days 00:00:04.936000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
3,0 days 00:00:06.465000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002FXT,NaN,False
4,0 days 00:00:11.553000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-0001HW,DFL-OBJ-002G68,True
5,0 days 00:00:15.097000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002G68,DFL-OBJ-002FYC,True
6,0 days 00:00:17.745000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002FYC,DFL-OBJ-002G68,True
7,0 days 00:00:23.130000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002G68,NaN,False
8,0 days 00:00:24.490000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
9,0 days 00:00:24.490000,GENERIC:OtherBallAction,DFL-CLU-00000P,NaN,DFL-OBJ-002GMO,NaN,NaN
10,0 days 00:00:30.170000,GENERIC:Delete,NaN,NaN,NaN,NaN,NaN
11,0 days 00:00:30.730000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-0028T3,NaN,False
12,0 days 00:00:31.090000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
13,0 days 00:00:38.129000,GENERIC:OtherBallAction,DFL-CLU-000005,NaN,DFL-OBJ-0000EJ,NaN,NaN
14,0 days 00:00:38.929000,GENERIC:Delete,NaN,NaN,NaN,NaN,NaN
15,0 days 00:00:41.161000,GENERIC:Delete,NaN,NaN,NaN,NaN,NaN
16,0 days 00:00:26.490000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
17,0 days 00:00:42.569000,BALL_OUT,NaN,NaN,NaN,NaN,NaN
18,0 days 00:00:47.832000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0000NZ,DFL-OBJ-002GMO,True
19,0 days 00:00:50.705000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002GMO,DFL-OBJ-0028FW,True
20,0 days 00:00:52.472000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0028FW,DFL-OBJ-0000NZ,True
21,0 days 00:00:59.425000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0000NZ,DFL-OBJ-00028V,True
22,0 days 00:00:28.890000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
23,0 days 00:01:00.608000,GENERIC:Delete,NaN,NaN,NaN,NaN,NaN
24,0 days 00:01:03.777000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-00028V,NaN,False
25,0 days 00:01:06.915000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002GG4,DFL-OBJ-0028T3,True
26,0 days 00:01:08.689000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-0028T3,DFL-OBJ-002GG4,True
27,0 days 00:01:10.641000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002GG4,DFL-OBJ-J0178P,True
28,0 days 00:01:09.849000,GENERIC:Delete,NaN,NaN,NaN,NaN,NaN
29,0 days 00:00:30.730000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
30,0 days 00:01:14.097000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-J0178P,DFL-OBJ-002FYC,True
31,0 days 00:01:19.832000,GENERIC:Delete,NaN,NaN,NaN,NaN,NaN
32,0 days 00:01:23.905000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002FYC,DFL-OBJ-002595,True
33,0 days 00:01:27.250000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002595,NaN,False
34,0 days 00:01:28.841000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
35,0 days 00:01:29.744000,GENERIC:OtherBallAction,DFL-CLU-00000P,NaN,DFL-OBJ-002GM9,NaN,NaN
36,0 days 00:01:34.681000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002G5J,NaN,True
37,0 days 00:00:32.530000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
38,0 days 00:01:35.937000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
39,0 days 00:01:36.433000,FOUL_COMMITTED,DFL-CLU-000005,NaN,DFL-OBJ-002G68,NaN,NaN
40,0 days 00:01:58.329000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-00028V,DFL-OBJ-002GM9,True
41,0 days 00:02:00.193000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002GM9,DFL-OBJ-J01KJ5,True
42,0 days 00:02:02.050000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-J01KJ5,DFL-OBJ-0028FW,True
43,0 days 00:02:06.217000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0028FW,DFL-OBJ-00028V,True
44,0 days 00:02:09.601000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-00028V,DFL-OBJ-002GMO,True
45,0 days 00:01:21.130000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-002FYC,DFL-OBJ-002595,True
46,0 days 00:02:16.450000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002GMO,DFL-OBJ-00028V,True
47,0 days 00:02:17.826000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-00028V,DFL-OBJ-002GM9,True
48,0 days 00:02:19.938000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002GM9,DFL-OBJ-0028FW,True
49,0 days 00:02:24.497000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0028FW,DFL-OBJ-002GMO,True

In [29]:
display(
    events[
        [
            "timestamp",
            "event_type",
            "team_id",
            "ball_owning_team",
            "player_id",
            "receiver_player_id",
            "success"
        ]
    ].head(100)
)

,timestamp,event_type,team_id,ball_owning_team,player_id,receiver_player_id,success
0,0 days 00:00:00,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002G5J,DFL-OBJ-0028FW,True
1,0 days 00:00:01.697000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-0028FW,DFL-OBJ-002FXT,True
2,0 days 00:00:04.936000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
3,0 days 00:00:06.465000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002FXT,NaN,False
4,0 days 00:00:11.553000,PASS,DFL-CLU-000005,NaN,DFL-OBJ-0001HW,DFL-OBJ-002G68,True
...,...,...,...,...,...,...,...
95,0 days 00:04:25.394000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-002GMO,DFL-OBJ-J01H9X,True
96,0 days 00:04:28.418000,PASS,DFL-CLU-00000P,NaN,DFL-OBJ-J01H9X,DFL-OBJ-002GM9,True
97,0 days 00:04:29.338000,GENERIC:OtherBallAction,DFL-CLU-00000P,NaN,DFL-OBJ-002GM9,NaN,NaN
98,0 days 00:04:31.083000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN
99,0 days 00:04:34.211000,GENERIC:TacklingGame,NaN,NaN,NaN,NaN,NaN

LANJUTAN RECOVERY

In [30]:
recovery = events[
    events["event_type"] == "RECOVERY"
]

display(
    recovery[
        [
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "coordinates_x",
            "coordinates_y",
            "success"
        ]
    ]
)

,timestamp,event_type,team_id,player_id,coordinates_x,coordinates_y,success
1560,-1 days +22:59:06.214000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002GG4,0.487619,0.873088,NaN
1561,-1 days +23:26:28.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-002GMO,0.758571,0.578235,NaN
1562,-1 days +23:26:40.856000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,0.249048,0.277353,NaN
1563,-1 days +23:28:18.865000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,0.663143,0.951324,NaN
1564,-1 days +23:28:50.473000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002FYC,0.646000,0.497059,NaN
1565,0 days 00:12:33.775000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,0.756667,0.803824,NaN
1566,0 days 00:16:24.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0000F8,0.676571,0.737500,NaN
1567,0 days 00:22:21.539000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-J01KJ5,0.188952,0.241912,NaN
1568,0 days 00:40:21.596000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0026IA,0.862571,0.822941,NaN
1569,0 days 00:45:13.598000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0001HW,0.966571,0.471912,NaN
1570,0 days 00:48:27.624000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0028FW,0.042000,0.492647,NaN
1571,0 days 00:45:39.494000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,0.699429,0.243382,NaN

In [31]:
recovery = events[
    events["event_type"] == "RECOVERY"
].copy()

recovery = recovery.sort_values("timestamp")

display(
    recovery[
        [
            "period_id",
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "coordinates_x",
            "coordinates_y"
        ]
    ]
)

,period_id,timestamp,event_type,team_id,player_id,coordinates_x,coordinates_y
1560,2,-1 days +22:59:06.214000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002GG4,0.487619,0.873088
1561,2,-1 days +23:26:28.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-002GMO,0.758571,0.578235
1562,2,-1 days +23:26:40.856000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,0.249048,0.277353
1563,2,-1 days +23:28:18.865000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,0.663143,0.951324
1564,2,-1 days +23:28:50.473000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002FYC,0.646000,0.497059
1565,2,0 days 00:12:33.775000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,0.756667,0.803824
1566,2,0 days 00:16:24.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0000F8,0.676571,0.737500
1567,2,0 days 00:22:21.539000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-J01KJ5,0.188952,0.241912
1568,2,0 days 00:40:21.596000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0026IA,0.862571,0.822941
1569,2,0 days 00:45:13.598000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0001HW,0.966571,0.471912
1571,2,0 days 00:45:39.494000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,0.699429,0.243382
1570,2,0 days 00:48:27.624000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0028FW,0.042000,0.492647

In [32]:
print(
    recovery["team_id"].value_counts()
)

team_id
DFL-CLU-000005    8
DFL-CLU-00000P    4
Name: count, dtype: int64

CEK RECOVERY

In [33]:
def show_context(events, timestamp, window=3):
    start = timestamp - pd.Timedelta(seconds=window)
    end = timestamp + pd.Timedelta(seconds=window)

    context = events[
        (events["timestamp"] >= start) &
        (events["timestamp"] <= end)
    ].copy()

    return context[
        [
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "receiver_player_id",
            "success"
        ]
    ].sort_values("timestamp")

In [34]:
first_recovery_time = recovery.iloc[0]["timestamp"]

display(
    show_context(events, first_recovery_time, window=5)
)

,timestamp,event_type,team_id,player_id,receiver_player_id,success
1560,-1 days +22:59:06.214000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002GG4,NaN,NaN

In [35]:
recovery = events[
    events["event_type"] == "RECOVERY"
].copy()

recovery = recovery.sort_values("timestamp")

display(
    recovery[
        [
            "period_id",
            "timestamp",
            "event_type",
            "team_id",
            "player_id",
            "coordinates_x",
            "coordinates_y"
        ]
    ]
)

,period_id,timestamp,event_type,team_id,player_id,coordinates_x,coordinates_y
1560,2,-1 days +22:59:06.214000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002GG4,0.487619,0.873088
1561,2,-1 days +23:26:28.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-002GMO,0.758571,0.578235
1562,2,-1 days +23:26:40.856000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,0.249048,0.277353
1563,2,-1 days +23:28:18.865000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,0.663143,0.951324
1564,2,-1 days +23:28:50.473000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002FYC,0.646000,0.497059
1565,2,0 days 00:12:33.775000,RECOVERY,DFL-CLU-000005,DFL-OBJ-002G68,0.756667,0.803824
1566,2,0 days 00:16:24.192000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0000F8,0.676571,0.737500
1567,2,0 days 00:22:21.539000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-J01KJ5,0.188952,0.241912
1568,2,0 days 00:40:21.596000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0026IA,0.862571,0.822941
1569,2,0 days 00:45:13.598000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0001HW,0.966571,0.471912
1571,2,0 days 00:45:39.494000,RECOVERY,DFL-CLU-000005,DFL-OBJ-0028T3,0.699429,0.243382
1570,2,0 days 00:48:27.624000,RECOVERY,DFL-CLU-00000P,DFL-OBJ-0028FW,0.042000,0.492647

In [36]:
print(recovery["team_id"].value_counts())

team_id
DFL-CLU-000005    8
DFL-CLU-00000P    4
Name: count, dtype: int64