In [42]:
import pandas as pd
from pathlib import Path

In [43]:
DATA_DIR = Path(
    r"C:\VAEP-Track\scripts\data\sportec_idsse"
)

MATCH_IDS = [
    "J03WPY",
    "J03WMX",
    "J03WN1",
    "J03WOH",
    "J03WOY",
    "J03WQQ",
    "J03WR9",
]

print("Data directory:", DATA_DIR)
print("Jumlah match:", len(MATCH_IDS))

Data directory: C:\VAEP-Track\scripts\data\sportec_idsse
Jumlah match: 7

In [44]:
def analyze_match(match_id):
    """
    Menganalisis satu pertandingan:
    - jumlah frame tracking
    - jumlah frame dengan ball_owning_team_id
    - jumlah perubahan possession
    - jumlah candidate saat bola aktif
    """

    tracking_path = DATA_DIR / f"{match_id}_tracking.csv"

    if not tracking_path.exists():
        print(f"[WARNING] File tidak ditemukan: {tracking_path}")
        return None

    # Load data
    tracking = pd.read_csv(tracking_path)

    # Timestamp
    tracking["timestamp"] = pd.to_timedelta(
        tracking["timestamp"],
        errors="coerce"
    )

    # Urutkan secara temporal
    tracking = tracking.sort_values(
        ["period_id", "timestamp", "frame_id"]
    ).reset_index(drop=True)

    # Tim penguasa bola pada frame sebelumnya
    tracking["prev_owning_team"] = (
        tracking
        .groupby("period_id")["ball_owning_team_id"]
        .shift(1)
    )

    # Perubahan possession
    tracking["team_changed"] = (
        tracking["ball_owning_team_id"].notna()
        & tracking["prev_owning_team"].notna()
        & (
            tracking["ball_owning_team_id"]
            != tracking["prev_owning_team"]
        )
    )

    # Semua perubahan possession
    possession_changes = tracking[
        tracking["team_changed"]
    ].copy()

    # Hanya ketika bola aktif
    active_changes = possession_changes[
        possession_changes["ball_state"] == "alive"
    ].copy()

    result = {
        "match_id": match_id,
        "tracking_frames": len(tracking),
        "owning_team_valid_frames":
            tracking["ball_owning_team_id"].notna().sum(),
        "all_possession_changes":
            len(possession_changes),
        "active_possession_changes":
            len(active_changes),
    }

    return result

In [45]:
print("=== HASIL DEBUG ===")

print("\nIsi results:")
print(results)

print("\nKolom summary_df:")
print(summary_df.columns.tolist())

print("\nIsi summary_df:")
display(summary_df)

=== HASIL DEBUG ===

Isi results:
[{'match_id': 'J03WPY', 'tracking_frames': 146211, 'owning_team_valid_frames': 146211, 'all_possession_changes': 390, 'active_possession_changes': 324}, {'match_id': 'J03WMX', 'tracking_frames': 145967, 'owning_team_valid_frames': 145967, 'all_possession_changes': 500, 'active_possession_changes': 408}, {'match_id': 'J03WN1', 'tracking_frames': 141561, 'owning_team_valid_frames': 141561, 'all_possession_changes': 467, 'active_possession_changes': 394}, {'match_id': 'J03WOH', 'tracking_frames': 137214, 'owning_team_valid_frames': 137214, 'all_possession_changes': 366, 'active_possession_changes': 301}, {'match_id': 'J03WOY', 'tracking_frames': 142536, 'owning_team_valid_frames': 142536, 'all_possession_changes': 416, 'active_possession_changes': 344}, {'match_id': 'J03WQQ', 'tracking_frames': 142345, 'owning_team_valid_frames': 142345, 'all_possession_changes': 362, 'active_possession_changes': 304}, {'match_id': 'J03WR9', 'tracking_frames': 146810, 'owning_team_valid_frames': 146810, 'all_possession_changes': 346, 'active_possession_changes': 278}]

Kolom summary_df:
['match_id', 'tracking_frames', 'owning_team_valid_frames', 'all_possession_changes', 'active_possession_changes']

Isi summary_df:

,match_id,tracking_frames,owning_team_valid_frames,all_possession_changes,active_possession_changes
0,J03WPY,146211,146211,390,324
1,J03WMX,145967,145967,500,408
2,J03WN1,141561,141561,467,394
3,J03WOH,137214,137214,366,301
4,J03WOY,142536,142536,416,344
5,J03WQQ,142345,142345,362,304
6,J03WR9,146810,146810,346,278

In [46]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path(
    r"C:\VAEP-Track\data\sportec_idsse"
)

MATCH_IDS = [
    "J03WPY",
    "J03WMX",
    "J03WN1",
    "J03WOH",
    "J03WOY",
    "J03WQQ",
    "J03WR9",
]


def analyze_match(match_id):

    tracking_path = DATA_DIR / f"{match_id}_tracking.csv"

    print(f"\n=== {match_id} ===")
    print("File:", tracking_path)

    # --------------------------------------
    # CEK FILE
    # --------------------------------------

    if not tracking_path.exists():
        print("STATUS: FILE TIDAK DITEMUKAN")
        return None

    # --------------------------------------
    # LOAD DATA
    # --------------------------------------

    try:
        tracking = pd.read_csv(tracking_path)
    except Exception as e:
        print("STATUS: GAGAL MEMBACA FILE")
        print("Error:", e)
        return None

    print("Tracking shape:", tracking.shape)

    # --------------------------------------
    # TIMESTAMP
    # --------------------------------------

    tracking["timestamp"] = pd.to_timedelta(
        tracking["timestamp"],
        errors="coerce"
    )

    # --------------------------------------
    # SORT
    # --------------------------------------

    tracking = tracking.sort_values(
        ["period_id", "timestamp", "frame_id"]
    ).reset_index(drop=True)

    # --------------------------------------
    # PREVIOUS OWNER
    # --------------------------------------

    tracking["prev_owning_team"] = (
        tracking
        .groupby("period_id")["ball_owning_team_id"]
        .shift(1)
    )

    # --------------------------------------
    # POSSESSION CHANGE
    # --------------------------------------

    tracking["team_changed"] = (
        tracking["ball_owning_team_id"].notna()
        & tracking["prev_owning_team"].notna()
        & (
            tracking["ball_owning_team_id"]
            != tracking["prev_owning_team"]
        )
    )

    # --------------------------------------
    # SEMUA POSSESSION CHANGE
    # --------------------------------------

    possession_changes = tracking[
        tracking["team_changed"]
    ].copy()

    # --------------------------------------
    # HANYA BOLA AKTIF
    # --------------------------------------

    active_changes = possession_changes[
        possession_changes["ball_state"] == "alive"
    ].copy()

    # --------------------------------------
    # HASIL
    # --------------------------------------

    result = {
        "match_id": match_id,
        "tracking_frames": len(tracking),
        "owning_team_valid_frames": int(
            tracking["ball_owning_team_id"].notna().sum()
        ),
        "all_possession_changes": len(
            possession_changes
        ),
        "active_possession_changes": len(
            active_changes
        ),
    }

    print(
        "Active possession changes:",
        result["active_possession_changes"]
    )

    return result

In [47]:
results = []

for match_id in MATCH_IDS:

    result = analyze_match(match_id)

    if result is not None:
        results.append(result)

print("\n================================")
print("HASIL AKHIR")
print("================================")

print("Jumlah pertandingan berhasil:", len(results))

summary_df = pd.DataFrame(results)

display(summary_df)

=== J03WPY ===
File: C:\VAEP-Track\data\sportec_idsse\J03WPY_tracking.csv
Tracking shape: (146211, 133)
Active possession changes: 324

=== J03WMX ===
File: C:\VAEP-Track\data\sportec_idsse\J03WMX_tracking.csv
Tracking shape: (145967, 137)
Active possession changes: 408

=== J03WN1 ===
File: C:\VAEP-Track\data\sportec_idsse\J03WN1_tracking.csv
Tracking shape: (141561, 125)
Active possession changes: 394

=== J03WOH ===
File: C:\VAEP-Track\data\sportec_idsse\J03WOH_tracking.csv
Tracking shape: (137214, 137)
Active possession changes: 301

=== J03WOY ===
File: C:\VAEP-Track\data\sportec_idsse\J03WOY_tracking.csv
Tracking shape: (142536, 137)
Active possession changes: 344

=== J03WQQ ===
File: C:\VAEP-Track\data\sportec_idsse\J03WQQ_tracking.csv
Tracking shape: (142345, 133)
Active possession changes: 304

=== J03WR9 ===
File: C:\VAEP-Track\data\sportec_idsse\J03WR9_tracking.csv
Tracking shape: (146810, 133)
Active possession changes: 278

================================
HASIL AKHIR
================================
Jumlah pertandingan berhasil: 7

,match_id,tracking_frames,owning_team_valid_frames,all_possession_changes,active_possession_changes
0,J03WPY,146211,146211,390,324
1,J03WMX,145967,145967,500,408
2,J03WN1,141561,141561,467,394
3,J03WOH,137214,137214,366,301
4,J03WOY,142536,142536,416,344
5,J03WQQ,142345,142345,362,304
6,J03WR9,146810,146810,346,278

In [48]:
print(
    "Kolom:",
    summary_df.columns.tolist()
)

print(
    "Total tracking frames:",
    summary_df["tracking_frames"].sum()
)

print(
    "Total possession changes:",
    summary_df["all_possession_changes"].sum()
)

print(
    "Total active possession changes:",
    summary_df["active_possession_changes"].sum()
)

Kolom: ['match_id', 'tracking_frames', 'owning_team_valid_frames', 'all_possession_changes', 'active_possession_changes']
Total tracking frames: 1002644
Total possession changes: 2847
Total active possession changes: 2353

In [49]:
import pandas as pd
from pathlib import Path

# ==========================================
# KONFIGURASI DATA
# ==========================================

DATA_DIR = Path(
    r"C:\VAEP-Track\data\sportec_idsse"
)

MATCH_IDS = [
    "J03WPY",
    "J03WMX",
    "J03WN1",
    "J03WOH",
    "J03WOY",
    "J03WQQ",
    "J03WR9",
]


# ==========================================
# FUNGSI MENGAMBIL ACTIVE POSSESSION CHANGE
# ==========================================

def get_active_possession_changes(match_id):

    tracking_path = DATA_DIR / f"{match_id}_tracking.csv"

    tracking = pd.read_csv(tracking_path)

    # Konversi timestamp
    tracking["timestamp"] = pd.to_timedelta(
        tracking["timestamp"],
        errors="coerce"
    )

    # Urutkan berdasarkan waktu
    tracking = tracking.sort_values(
        ["period_id", "timestamp", "frame_id"]
    ).reset_index(drop=True)

    # Tim yang menguasai bola pada frame sebelumnya
    tracking["prev_owning_team"] = (
        tracking
        .groupby("period_id")["ball_owning_team_id"]
        .shift(1)
    )

    # Perubahan penguasaan
    changes = tracking[
        tracking["ball_owning_team_id"].notna()
        & tracking["prev_owning_team"].notna()
        & (
            tracking["ball_owning_team_id"]
            != tracking["prev_owning_team"]
        )
        & (
            tracking["ball_state"] == "alive"
        )
    ].copy()

    # Tambahkan ID pertandingan
    changes["match_id"] = match_id

    return changes


# ==========================================
# GABUNGKAN 7 PERTANDINGAN
# ==========================================

all_candidates = []

for match_id in MATCH_IDS:

    print(f"Memproses {match_id}...")

    changes = get_active_possession_changes(match_id)

    all_candidates.append(changes)

all_candidates_df = pd.concat(
    all_candidates,
    ignore_index=True
)

print("\n===================================")
print("TOTAL ACTIVE POSSESSION CHANGES")
print("===================================")

print(
    "Jumlah total:",
    len(all_candidates_df)
)

Memproses J03WPY...
Memproses J03WMX...
Memproses J03WN1...
Memproses J03WOH...
Memproses J03WOY...
Memproses J03WQQ...
Memproses J03WR9...

===================================
TOTAL ACTIVE POSSESSION CHANGES
===================================
Jumlah total: 2353

In [50]:
# ==========================================
# ANALISIS JARAK ANTAR POSSESSION CHANGE
# ==========================================

changes_time = all_candidates_df.copy()

# Urutkan berdasarkan pertandingan, babak, dan waktu
changes_time = changes_time.sort_values(
    ["match_id", "period_id", "timestamp"]
).reset_index(drop=True)

# Timestamp candidate sebelumnya
changes_time["prev_change_timestamp"] = (
    changes_time
    .groupby(["match_id", "period_id"])["timestamp"]
    .shift(1)
)

# Hitung selisih waktu
changes_time["gap_seconds"] = (
    changes_time["timestamp"]
    - changes_time["prev_change_timestamp"]
).dt.total_seconds()

display(
    changes_time[
        [
            "match_id",
            "period_id",
            "timestamp",
            "prev_owning_team",
            "ball_owning_team_id",
            "gap_seconds"
        ]
    ].head(30)
)

,match_id,period_id,timestamp,prev_owning_team,ball_owning_team_id,gap_seconds
0,J03WMX,1,0 days 00:00:23.480000,DFL-CLU-000008,DFL-CLU-00000G,NaN
1,J03WMX,1,0 days 00:00:42.840000,DFL-CLU-00000G,DFL-CLU-000008,19.36
2,J03WMX,1,0 days 00:00:49.520000,DFL-CLU-000008,DFL-CLU-00000G,6.68
3,J03WMX,1,0 days 00:01:22.040000,DFL-CLU-00000G,DFL-CLU-000008,32.52
4,J03WMX,1,0 days 00:01:25.320000,DFL-CLU-000008,DFL-CLU-00000G,3.28
5,J03WMX,1,0 days 00:01:32.760000,DFL-CLU-00000G,DFL-CLU-000008,7.44
6,J03WMX,1,0 days 00:02:09.760000,DFL-CLU-00000G,DFL-CLU-000008,37.00
7,J03WMX,1,0 days 00:02:14.680000,DFL-CLU-000008,DFL-CLU-00000G,4.92
8,J03WMX,1,0 days 00:02:23.560000,DFL-CLU-00000G,DFL-CLU-000008,8.88
9,J03WMX,1,0 days 00:02:25.160000,DFL-CLU-000008,DFL-CLU-00000G,1.60
10,J03WMX,1,0 days 00:02:30.040000,DFL-CLU-00000G,DFL-CLU-000008,4.88
11,J03WMX,1,0 days 00:03:08.840000,DFL-CLU-00000G,DFL-CLU-000008,38.80
12,J03WMX,1,0 days 00:03:19.120000,DFL-CLU-000008,DFL-CLU-00000G,10.28
13,J03WMX,1,0 days 00:03:46.040000,DFL-CLU-00000G,DFL-CLU-000008,26.92
14,J03WMX,1,0 days 00:04:34.680000,DFL-CLU-00000G,DFL-CLU-000008,48.64
15,J03WMX,1,0 days 00:04:34.920000,DFL-CLU-000008,DFL-CLU-00000G,0.24
16,J03WMX,1,0 days 00:04:36.600000,DFL-CLU-00000G,DFL-CLU-000008,1.68
17,J03WMX,1,0 days 00:04:51.200000,DFL-CLU-00000G,DFL-CLU-000008,14.60
18,J03WMX,1,0 days 00:05:04.880000,DFL-CLU-00000G,DFL-CLU-000008,13.68
19,J03WMX,1,0 days 00:05:06.040000,DFL-CLU-000008,DFL-CLU-00000G,1.16
20,J03WMX,1,0 days 00:05:36.680000,DFL-CLU-00000G,DFL-CLU-000008,30.64
21,J03WMX,1,0 days 00:05:40.040000,DFL-CLU-000008,DFL-CLU-00000G,3.36
22,J03WMX,1,0 days 00:05:52.680000,DFL-CLU-00000G,DFL-CLU-000008,12.64
23,J03WMX,1,0 days 00:05:53.680000,DFL-CLU-000008,DFL-CLU-00000G,1.00
24,J03WMX,1,0 days 00:06:01.680000,DFL-CLU-00000G,DFL-CLU-000008,8.00
25,J03WMX,1,0 days 00:06:02.240000,DFL-CLU-000008,DFL-CLU-00000G,0.56
26,J03WMX,1,0 days 00:06:03.360000,DFL-CLU-00000G,DFL-CLU-000008,1.12
27,J03WMX,1,0 days 00:06:04.920000,DFL-CLU-000008,DFL-CLU-00000G,1.56
28,J03WMX,1,0 days 00:06:10.040000,DFL-CLU-00000G,DFL-CLU-000008,5.12
29,J03WMX,1,0 days 00:06:11.040000,DFL-CLU-000008,DFL-CLU-00000G,1.00

In [51]:
gap_stats = changes_time["gap_seconds"].dropna()

print("Jumlah gap:", len(gap_stats))

print("\nStatistik gap:")
print(
    gap_stats.describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

print("Gap <= 0.5 detik:",
      (gap_stats <= 0.5).sum())

print("Gap <= 1 detik:",
      (gap_stats <= 1.0).sum())

print("Gap <= 2 detik:",
      (gap_stats <= 2.0).sum())

print("Gap > 2 detik:",
      (gap_stats > 2.0).sum())

print("Gap > 5 detik:",
      (gap_stats > 5.0).sum())

Jumlah gap: 2339

Statistik gap:
count    2339.000000
mean       16.854656
std        25.015458
min         0.040000
25%         2.160000
50%         5.640000
75%        23.220000
90%        47.360000
95%        63.900000
max       266.840000
Name: gap_seconds, dtype: float64
Gap <= 0.5 detik: 91
Gap <= 1 detik: 224
Gap <= 2 detik: 529
Gap > 2 detik: 1810
Gap > 5 detik: 1234

ANALISIS REGAIN POSESSION

In [52]:
# ==========================================
# MENCARI POTENTIAL REGAIN ≤ 5 DETIK
# ==========================================

df = all_candidates_df.copy()

# Urutkan berdasarkan match, period, timestamp
df = df.sort_values(
    ["match_id", "period_id", "timestamp"]
).reset_index(drop=True)

# Candidate berikutnya dalam match + period yang sama
df["next_timestamp"] = (
    df.groupby(
        ["match_id", "period_id"]
    )["timestamp"].shift(-1)
)

df["next_losing_team"] = (
    df.groupby(
        ["match_id", "period_id"]
    )["prev_owning_team"].shift(-1)
)

df["next_gaining_team"] = (
    df.groupby(
        ["match_id", "period_id"]
    )["ball_owning_team_id"].shift(-1)
)

# Waktu menuju candidate berikutnya
df["next_gap_seconds"] = (
    df["next_timestamp"] - df["timestamp"]
).dt.total_seconds()

# Apakah possession berikutnya kembali
# ke tim yang kehilangan bola?
df["potential_regain"] = (
    (df["next_gap_seconds"] <= 5.0)
    &
    (
        df["next_gaining_team"]
        == df["prev_owning_team"]
    )
)

print(
    "Total candidate:",
    len(df)
)

print(
    "Potential regain ≤ 5 detik:",
    df["potential_regain"].sum()
)

print(
    "Persentase:",
    round(
        df["potential_regain"].mean() * 100,
        2
    ),
    "%"
)

Total candidate: 2353
Potential regain ≤ 5 detik: 1105
Persentase: 46.96 %

In [53]:
# ==========================================
# CEK DATA POTENTIAL REGAIN
# ==========================================

print("Jumlah event:", len(df))

print("\nKolom:")
print(df.columns.tolist())

print("\nContoh:")
display(df.head())

Jumlah event: 2353

Kolom:
['period_id', 'timestamp', 'frame_id', 'ball_state', 'ball_owning_team_id', 'ball_x', 'ball_y', 'ball_z', 'ball_speed', 'DFL-OBJ-0000NZ_x', 'DFL-OBJ-0000NZ_y', 'DFL-OBJ-0000NZ_d', 'DFL-OBJ-0000NZ_s', 'DFL-OBJ-0000F8_x', 'DFL-OBJ-0000F8_y', 'DFL-OBJ-0000F8_d', 'DFL-OBJ-0000F8_s', 'DFL-OBJ-00028V_x', 'DFL-OBJ-00028V_y', 'DFL-OBJ-00028V_d', 'DFL-OBJ-00028V_s', 'DFL-OBJ-002FXT_x', 'DFL-OBJ-002FXT_y', 'DFL-OBJ-002FXT_d', 'DFL-OBJ-002FXT_s', 'DFL-OBJ-0026RH_x', 'DFL-OBJ-0026RH_y', 'DFL-OBJ-0026RH_d', 'DFL-OBJ-0026RH_s', 'DFL-OBJ-0028FW_x', 'DFL-OBJ-0028FW_y', 'DFL-OBJ-0028FW_d', 'DFL-OBJ-0028FW_s', 'DFL-OBJ-002G5J_x', 'DFL-OBJ-002G5J_y', 'DFL-OBJ-002G5J_d', 'DFL-OBJ-002G5J_s', 'DFL-OBJ-002GMO_x', 'DFL-OBJ-002GMO_y', 'DFL-OBJ-002GMO_d', 'DFL-OBJ-002GMO_s', 'DFL-OBJ-002GM9_x', 'DFL-OBJ-002GM9_y', 'DFL-OBJ-002GM9_d', 'DFL-OBJ-002GM9_s', 'DFL-OBJ-J01H9X_x', 'DFL-OBJ-J01H9X_y', 'DFL-OBJ-J01H9X_d', 'DFL-OBJ-J01H9X_s', 'DFL-OBJ-J01KJ5_x', 'DFL-OBJ-J01KJ5_y', 'DFL-OBJ-J01KJ5_d', 'DFL-OBJ-J01KJ5_s', 'DFL-OBJ-00008F_x', 'DFL-OBJ-00008F_y', 'DFL-OBJ-00008F_d', 'DFL-OBJ-00008F_s', 'DFL-OBJ-0000EJ_x', 'DFL-OBJ-0000EJ_y', 'DFL-OBJ-0000EJ_d', 'DFL-OBJ-0000EJ_s', 'DFL-OBJ-0001HW_x', 'DFL-OBJ-0001HW_y', 'DFL-OBJ-0001HW_d', 'DFL-OBJ-0001HW_s', 'DFL-OBJ-0001LJ_x', 'DFL-OBJ-0001LJ_y', 'DFL-OBJ-0001LJ_d', 'DFL-OBJ-0001LJ_s', 'DFL-OBJ-002595_x', 'DFL-OBJ-002595_y', 'DFL-OBJ-002595_d', 'DFL-OBJ-002595_s', 'DFL-OBJ-J0178P_x', 'DFL-OBJ-J0178P_y', 'DFL-OBJ-J0178P_d', 'DFL-OBJ-J0178P_s', 'DFL-OBJ-0028BZ_x', 'DFL-OBJ-0028BZ_y', 'DFL-OBJ-0028BZ_d', 'DFL-OBJ-0028BZ_s', 'DFL-OBJ-0028T3_x', 'DFL-OBJ-0028T3_y', 'DFL-OBJ-0028T3_d', 'DFL-OBJ-0028T3_s', 'DFL-OBJ-002G68_x', 'DFL-OBJ-002G68_y', 'DFL-OBJ-002G68_d', 'DFL-OBJ-002G68_s', 'DFL-OBJ-002FYC_x', 'DFL-OBJ-002FYC_y', 'DFL-OBJ-002FYC_d', 'DFL-OBJ-002FYC_s', 'DFL-OBJ-002GG4_x', 'DFL-OBJ-002GG4_y', 'DFL-OBJ-002GG4_d', 'DFL-OBJ-002GG4_s', 'DFL-OBJ-J01CP5_x', 'DFL-OBJ-J01CP5_y', 'DFL-OBJ-J01CP5_d', 'DFL-OBJ-J01CP5_s', 'DFL-OBJ-J01NQ8_x', 'DFL-OBJ-J01NQ8_y', 'DFL-OBJ-J01NQ8_d', 'DFL-OBJ-J01NQ8_s', 'DFL-OBJ-00008K_x', 'DFL-OBJ-00008K_y', 'DFL-OBJ-00008K_d', 'DFL-OBJ-00008K_s', 'DFL-OBJ-0026IA_x', 'DFL-OBJ-0026IA_y', 'DFL-OBJ-0026IA_d', 'DFL-OBJ-0026IA_s', 'DFL-OBJ-002G78_x', 'DFL-OBJ-002G78_y', 'DFL-OBJ-002G78_d', 'DFL-OBJ-002G78_s', 'DFL-OBJ-00286U_x', 'DFL-OBJ-00286U_y', 'DFL-OBJ-00286U_d', 'DFL-OBJ-00286U_s', 'DFL-OBJ-002GM1_x', 'DFL-OBJ-002GM1_y', 'DFL-OBJ-002GM1_d', 'DFL-OBJ-002GM1_s', 'DFL-OBJ-J01K2L_x', 'DFL-OBJ-J01K2L_y', 'DFL-OBJ-J01K2L_d', 'DFL-OBJ-J01K2L_s', 'DFL-OBJ-0001BX_x', 'DFL-OBJ-0001BX_y', 'DFL-OBJ-0001BX_d', 'DFL-OBJ-0001BX_s', 'prev_owning_team', 'match_id', 'DFL-OBJ-0002DR_x', 'DFL-OBJ-0002DR_y', 'DFL-OBJ-0002DR_d', 'DFL-OBJ-0002DR_s', 'DFL-OBJ-0000IA_x', 'DFL-OBJ-0000IA_y', 'DFL-OBJ-0000IA_d', 'DFL-OBJ-0000IA_s', 'DFL-OBJ-0027G6_x', 'DFL-OBJ-0027G6_y', 'DFL-OBJ-0027G6_d', 'DFL-OBJ-0027G6_s', 'DFL-OBJ-0002F5_x', 'DFL-OBJ-0002F5_y', 'DFL-OBJ-0002F5_d', 'DFL-OBJ-0002F5_s', 'DFL-OBJ-0026PM_x', 'DFL-OBJ-0026PM_y', 'DFL-OBJ-0026PM_d', 'DFL-OBJ-0026PM_s', 'DFL-OBJ-0002AU_x', 'DFL-OBJ-0002AU_y', 'DFL-OBJ-0002AU_d', 'DFL-OBJ-0002AU_s', 'DFL-OBJ-0027KL_x', 'DFL-OBJ-0027KL_y', 'DFL-OBJ-0027KL_d', 'DFL-OBJ-0027KL_s', 'DFL-OBJ-0027G0_x', 'DFL-OBJ-0027G0_y', 'DFL-OBJ-0027G0_d', 'DFL-OBJ-0027G0_s', 'DFL-OBJ-J017RE_x', 'DFL-OBJ-J017RE_y', 'DFL-OBJ-J017RE_d', 'DFL-OBJ-J017RE_s', 'DFL-OBJ-J01APO_x', 'DFL-OBJ-J01APO_y', 'DFL-OBJ-J01APO_d', 'DFL-OBJ-J01APO_s', 'DFL-OBJ-J01B8N_x', 'DFL-OBJ-J01B8N_y', 'DFL-OBJ-J01B8N_d', 'DFL-OBJ-J01B8N_s', 'DFL-OBJ-0027AX_x', 'DFL-OBJ-0027AX_y', 'DFL-OBJ-0027AX_d', 'DFL-OBJ-0027AX_s', 'DFL-OBJ-00012X_x', 'DFL-OBJ-00012X_y', 'DFL-OBJ-00012X_d', 'DFL-OBJ-00012X_s', 'DFL-OBJ-000270_x', 'DFL-OBJ-000270_y', 'DFL-OBJ-000270_d', 'DFL-OBJ-000270_s', 'DFL-OBJ-0002HE_x', 'DFL-OBJ-0002HE_y', 'DFL-OBJ-0002HE_d', 'DFL-OBJ-0002HE_s', 'DFL-OBJ-0002BO_x', 'DFL-OBJ-0002BO_y', 'DFL-OBJ-0002BO_d', 'DFL-OBJ-0002BO_s', 'DFL-OBJ-0027B6_x', 'DFL-OBJ-0027B6_y', 'DFL-OBJ-0027B6_d', 'DFL-OBJ-0027B6_s', 'DFL-OBJ-0028BD_x', 'DFL-OBJ-0028BD_y', 'DFL-OBJ-0028BD_d', 'DFL-OBJ-0028BD_s', 'DFL-OBJ-002G4A_x', 'DFL-OBJ-002G4A_y', 'DFL-OBJ-002G4A_d', 'DFL-OBJ-002G4A_s', 'DFL-OBJ-J01BGM_x', 'DFL-OBJ-J01BGM_y', 'DFL-OBJ-J01BGM_d', 'DFL-OBJ-J01BGM_s', 'DFL-OBJ-J01D1W_x', 'DFL-OBJ-J01D1W_y', 'DFL-OBJ-J01D1W_d', 'DFL-OBJ-J01D1W_s', 'DFL-OBJ-002GKO_x', 'DFL-OBJ-002GKO_y', 'DFL-OBJ-002GKO_d', 'DFL-OBJ-002GKO_s', 'DFL-OBJ-0027V2_x', 'DFL-OBJ-0027V2_y', 'DFL-OBJ-0027V2_d', 'DFL-OBJ-0027V2_s', 'DFL-OBJ-002G89_x', 'DFL-OBJ-002G89_y', 'DFL-OBJ-002G89_d', 'DFL-OBJ-002G89_s', 'DFL-OBJ-J01DVC_x', 'DFL-OBJ-J01DVC_y', 'DFL-OBJ-J01DVC_d', 'DFL-OBJ-J01DVC_s', 'DFL-OBJ-J015S4_x', 'DFL-OBJ-J015S4_y', 'DFL-OBJ-J015S4_d', 'DFL-OBJ-J015S4_s', 'DFL-OBJ-000191_x', 'DFL-OBJ-000191_y', 'DFL-OBJ-000191_d', 'DFL-OBJ-000191_s', 'DFL-OBJ-0000RP_x', 'DFL-OBJ-0000RP_y', 'DFL-OBJ-0000RP_d', 'DFL-OBJ-0000RP_s', 'DFL-OBJ-0026ZI_x', 'DFL-OBJ-0026ZI_y', 'DFL-OBJ-0026ZI_d', 'DFL-OBJ-0026ZI_s', 'DFL-OBJ-002GBW_x', 'DFL-OBJ-002GBW_y', 'DFL-OBJ-002GBW_d', 'DFL-OBJ-002GBW_s', 'DFL-OBJ-J01N65_x', 'DFL-OBJ-J01N65_y', 'DFL-OBJ-J01N65_d', 'DFL-OBJ-J01N65_s', 'DFL-OBJ-002GCR_x', 'DFL-OBJ-002GCR_y', 'DFL-OBJ-002GCR_d', 'DFL-OBJ-002GCR_s', 'DFL-OBJ-0001I0_x', 'DFL-OBJ-0001I0_y', 'DFL-OBJ-0001I0_d', 'DFL-OBJ-0001I0_s', 'DFL-OBJ-000172_x', 'DFL-OBJ-000172_y', 'DFL-OBJ-000172_d', 'DFL-OBJ-000172_s', 'DFL-OBJ-0000YV_x', 'DFL-OBJ-0000YV_y', 'DFL-OBJ-0000YV_d', 'DFL-OBJ-0000YV_s', 'DFL-OBJ-0000XU_x', 'DFL-OBJ-0000XU_y', 'DFL-OBJ-0000XU_d', 'DFL-OBJ-0000XU_s', 'DFL-OBJ-000199_x', 'DFL-OBJ-000199_y', 'DFL-OBJ-000199_d', 'DFL-OBJ-000199_s', 'DFL-OBJ-J014F7_x', 'DFL-OBJ-J014F7_y', 'DFL-OBJ-J014F7_d', 'DFL-OBJ-J014F7_s', 'DFL-OBJ-J016C3_x', 'DFL-OBJ-J016C3_y', 'DFL-OBJ-J016C3_d', 'DFL-OBJ-J016C3_s', 'DFL-OBJ-0027FG_x', 'DFL-OBJ-0027FG_y', 'DFL-OBJ-0027FG_d', 'DFL-OBJ-0027FG_s', 'DFL-OBJ-0027LO_x', 'DFL-OBJ-0027LO_y', 'DFL-OBJ-0027LO_d', 'DFL-OBJ-0027LO_s', 'DFL-OBJ-0028NB_x', 'DFL-OBJ-0028NB_y', 'DFL-OBJ-0028NB_d', 'DFL-OBJ-0028NB_s', 'DFL-OBJ-002GM0_x', 'DFL-OBJ-002GM0_y', 'DFL-OBJ-002GM0_d', 'DFL-OBJ-002GM0_s', 'DFL-OBJ-0026NY_x', 'DFL-OBJ-0026NY_y', 'DFL-OBJ-0026NY_d', 'DFL-OBJ-0026NY_s', 'DFL-OBJ-0001UP_x', 'DFL-OBJ-0001UP_y', 'DFL-OBJ-0001UP_d', 'DFL-OBJ-0001UP_s', 'DFL-OBJ-J013O2_x', 'DFL-OBJ-J013O2_y', 'DFL-OBJ-J013O2_d', 'DFL-OBJ-J013O2_s', 'DFL-OBJ-0002LI_x', 'DFL-OBJ-0002LI_y', 'DFL-OBJ-0002LI_d', 'DFL-OBJ-0002LI_s', 'DFL-OBJ-002G02_x', 'DFL-OBJ-002G02_y', 'DFL-OBJ-002G02_d', 'DFL-OBJ-002G02_s', 'DFL-OBJ-J01B8R_x', 'DFL-OBJ-J01B8R_y', 'DFL-OBJ-J01B8R_d', 'DFL-OBJ-J01B8R_s', 'DFL-OBJ-002GAR_x', 'DFL-OBJ-002GAR_y', 'DFL-OBJ-002GAR_d', 'DFL-OBJ-002GAR_s', 'DFL-OBJ-002G8H_x', 'DFL-OBJ-002G8H_y', 'DFL-OBJ-002G8H_d', 'DFL-OBJ-002G8H_s', 'DFL-OBJ-002GOI_x', 'DFL-OBJ-002GOI_y', 'DFL-OBJ-002GOI_d', 'DFL-OBJ-002GOI_s', 'DFL-OBJ-002GBK_x', 'DFL-OBJ-002GBK_y', 'DFL-OBJ-002GBK_d', 'DFL-OBJ-002GBK_s', 'DFL-OBJ-J01KDN_x', 'DFL-OBJ-J01KDN_y', 'DFL-OBJ-J01KDN_d', 'DFL-OBJ-J01KDN_s', 'DFL-OBJ-0028D6_x', 'DFL-OBJ-0028D6_y', 'DFL-OBJ-0028D6_d', 'DFL-OBJ-0028D6_s', 'DFL-OBJ-002G4G_x', 'DFL-OBJ-002G4G_y', 'DFL-OBJ-002G4G_d', 'DFL-OBJ-002G4G_s', 'DFL-OBJ-J01G0J_x', 'DFL-OBJ-J01G0J_y', 'DFL-OBJ-J01G0J_d', 'DFL-OBJ-J01G0J_s', 'DFL-OBJ-J01AQV_x', 'DFL-OBJ-J01AQV_y', 'DFL-OBJ-J01AQV_d', 'DFL-OBJ-J01AQV_s', 'DFL-OBJ-00002Z_x', 'DFL-OBJ-00002Z_y', 'DFL-OBJ-00002Z_d', 'DFL-OBJ-00002Z_s', 'DFL-OBJ-002GAV_x', 'DFL-OBJ-002GAV_y', 'DFL-OBJ-002GAV_d', 'DFL-OBJ-002GAV_s', 'DFL-OBJ-J01K4C_x', 'DFL-OBJ-J01K4C_y', 'DFL-OBJ-J01K4C_d', 'DFL-OBJ-J01K4C_s', 'DFL-OBJ-00003X_x', 'DFL-OBJ-00003X_y', 'DFL-OBJ-00003X_d', 'DFL-OBJ-00003X_s', 'DFL-OBJ-00006V_x', 'DFL-OBJ-00006V_y', 'DFL-OBJ-00006V_d', 'DFL-OBJ-00006V_s', 'DFL-OBJ-J0130T_x', 'DFL-OBJ-J0130T_y', 'DFL-OBJ-J0130T_d', 'DFL-OBJ-J0130T_s', 'DFL-OBJ-J014UG_x', 'DFL-OBJ-J014UG_y', 'DFL-OBJ-J014UG_d', 'DFL-OBJ-J014UG_s', 'DFL-OBJ-0026UQ_x', 'DFL-OBJ-0026UQ_y', 'DFL-OBJ-0026UQ_d', 'DFL-OBJ-0026UQ_s', 'DFL-OBJ-002651_x', 'DFL-OBJ-002651_y', 'DFL-OBJ-002651_d', 'DFL-OBJ-002651_s', 'DFL-OBJ-0027XP_x', 'DFL-OBJ-0027XP_y', 'DFL-OBJ-0027XP_d', 'DFL-OBJ-0027XP_s', 'DFL-OBJ-00268T_x', 'DFL-OBJ-00268T_y', 'DFL-OBJ-00268T_d', 'DFL-OBJ-00268T_s', 'DFL-OBJ-0027B0_x', 'DFL-OBJ-0027B0_y', 'DFL-OBJ-0027B0_d', 'DFL-OBJ-0027B0_s', 'DFL-OBJ-002GNH_x', 'DFL-OBJ-002GNH_y', 'DFL-OBJ-002GNH_d', 'DFL-OBJ-002GNH_s', 'DFL-OBJ-0027VS_x', 'DFL-OBJ-0027VS_y', 'DFL-OBJ-0027VS_d', 'DFL-OBJ-0027VS_s', 'DFL-OBJ-002GAB_x', 'DFL-OBJ-002GAB_y', 'DFL-OBJ-002GAB_d', 'DFL-OBJ-002GAB_s', 'DFL-OBJ-0028SW_x', 'DFL-OBJ-0028SW_y', 'DFL-OBJ-0028SW_d', 'DFL-OBJ-0028SW_s', 'DFL-OBJ-002G2Y_x', 'DFL-OBJ-002G2Y_y', 'DFL-OBJ-002G2Y_d', 'DFL-OBJ-002G2Y_s', 'DFL-OBJ-002GEE_x', 'DFL-OBJ-002GEE_y', 'DFL-OBJ-002GEE_d', 'DFL-OBJ-002GEE_s', 'DFL-OBJ-002GFH_x', 'DFL-OBJ-002GFH_y', 'DFL-OBJ-002GFH_d', 'DFL-OBJ-002GFH_s', 'DFL-OBJ-0028OR_x', 'DFL-OBJ-0028OR_y', 'DFL-OBJ-0028OR_d', 'DFL-OBJ-0028OR_s', 'DFL-OBJ-0028CD_x', 'DFL-OBJ-0028CD_y', 'DFL-OBJ-0028CD_d', 'DFL-OBJ-0028CD_s', 'DFL-OBJ-J01L1F_x', 'DFL-OBJ-J01L1F_y', 'DFL-OBJ-J01L1F_d', 'DFL-OBJ-J01L1F_s', 'DFL-OBJ-002GDZ_x', 'DFL-OBJ-002GDZ_y', 'DFL-OBJ-002GDZ_d', 'DFL-OBJ-002GDZ_s', 'DFL-OBJ-0027P7_x', 'DFL-OBJ-0027P7_y', 'DFL-OBJ-0027P7_d', 'DFL-OBJ-0027P7_s', 'DFL-OBJ-002FZB_x', 'DFL-OBJ-002FZB_y', 'DFL-OBJ-002FZB_d', 'DFL-OBJ-002FZB_s', 'DFL-OBJ-00019R_x', 'DFL-OBJ-00019R_y', 'DFL-OBJ-00019R_d', 'DFL-OBJ-00019R_s', 'DFL-OBJ-0001IG_x', 'DFL-OBJ-0001IG_y', 'DFL-OBJ-0001IG_d', 'DFL-OBJ-0001IG_s', 'DFL-OBJ-002FXA_x', 'DFL-OBJ-002FXA_y', 'DFL-OBJ-002FXA_d', 'DFL-OBJ-002FXA_s', 'DFL-OBJ-0025BB_x', 'DFL-OBJ-0025BB_y', 'DFL-OBJ-0025BB_d', 'DFL-OBJ-0025BB_s', 'DFL-OBJ-0026ZT_x', 'DFL-OBJ-0026ZT_y', 'DFL-OBJ-0026ZT_d', 'DFL-OBJ-0026ZT_s', 'DFL-OBJ-J0196K_x', 'DFL-OBJ-J0196K_y', 'DFL-OBJ-J0196K_d', 'DFL-OBJ-J0196K_s', 'DFL-OBJ-00286X_x', 'DFL-OBJ-00286X_y', 'DFL-OBJ-00286X_d', 'DFL-OBJ-00286X_s', 'DFL-OBJ-0028KZ_x', 'DFL-OBJ-0028KZ_y', 'DFL-OBJ-0028KZ_d', 'DFL-OBJ-0028KZ_s', 'DFL-OBJ-002GLL_x', 'DFL-OBJ-002GLL_y', 'DFL-OBJ-002GLL_d', 'DFL-OBJ-002GLL_s', 'DFL-OBJ-J01KGY_x', 'DFL-OBJ-J01KGY_y', 'DFL-OBJ-J01KGY_d', 'DFL-OBJ-J01KGY_s', 'DFL-OBJ-J01GG9_x', 'DFL-OBJ-J01GG9_y', 'DFL-OBJ-J01GG9_d', 'DFL-OBJ-J01GG9_s', 'DFL-OBJ-0028IJ_x', 'DFL-OBJ-0028IJ_y', 'DFL-OBJ-0028IJ_d', 'DFL-OBJ-0028IJ_s', 'DFL-OBJ-0001CF_x', 'DFL-OBJ-0001CF_y', 'DFL-OBJ-0001CF_d', 'DFL-OBJ-0001CF_s', 'DFL-OBJ-J01MF0_x', 'DFL-OBJ-J01MF0_y', 'DFL-OBJ-J01MF0_d', 'DFL-OBJ-J01MF0_s', 'DFL-OBJ-0028JQ_x', 'DFL-OBJ-0028JQ_y', 'DFL-OBJ-0028JQ_d', 'DFL-OBJ-0028JQ_s', 'DFL-OBJ-J01JQC_x', 'DFL-OBJ-J01JQC_y', 'DFL-OBJ-J01JQC_d', 'DFL-OBJ-J01JQC_s', 'DFL-OBJ-0002EL_x', 'DFL-OBJ-0002EL_y', 'DFL-OBJ-0002EL_d', 'DFL-OBJ-0002EL_s', 'DFL-OBJ-J014L2_x', 'DFL-OBJ-J014L2_y', 'DFL-OBJ-J014L2_d', 'DFL-OBJ-J014L2_s', 'DFL-OBJ-J0157X_x', 'DFL-OBJ-J0157X_y', 'DFL-OBJ-J0157X_d', 'DFL-OBJ-J0157X_s', 'DFL-OBJ-0026V5_x', 'DFL-OBJ-0026V5_y', 'DFL-OBJ-0026V5_d', 'DFL-OBJ-0026V5_s', 'DFL-OBJ-0027QN_x', 'DFL-OBJ-0027QN_y', 'DFL-OBJ-0027QN_d', 'DFL-OBJ-0027QN_s', 'DFL-OBJ-0028LZ_x', 'DFL-OBJ-0028LZ_y', 'DFL-OBJ-0028LZ_d', 'DFL-OBJ-0028LZ_s', 'DFL-OBJ-002FZR_x', 'DFL-OBJ-002FZR_y', 'DFL-OBJ-002FZR_d', 'DFL-OBJ-002FZR_s', 'DFL-OBJ-002GNL_x', 'DFL-OBJ-002GNL_y', 'DFL-OBJ-002GNL_d', 'DFL-OBJ-002GNL_s', 'DFL-OBJ-002GIY_x', 'DFL-OBJ-002GIY_y', 'DFL-OBJ-002GIY_d', 'DFL-OBJ-002GIY_s', 'DFL-OBJ-002GN4_x', 'DFL-OBJ-002GN4_y', 'DFL-OBJ-002GN4_d', 'DFL-OBJ-002GN4_s', 'DFL-OBJ-J01PRP_x', 'DFL-OBJ-J01PRP_y', 'DFL-OBJ-J01PRP_d', 'DFL-OBJ-J01PRP_s', 'DFL-OBJ-0027W9_x', 'DFL-OBJ-0027W9_y', 'DFL-OBJ-0027W9_d', 'DFL-OBJ-0027W9_s', 'DFL-OBJ-0028HW_x', 'DFL-OBJ-0028HW_y', 'DFL-OBJ-0028HW_d', 'DFL-OBJ-0028HW_s', 'DFL-OBJ-J01HCH_x', 'DFL-OBJ-J01HCH_y', 'DFL-OBJ-J01HCH_d', 'DFL-OBJ-J01HCH_s', 'DFL-OBJ-00005H_x', 'DFL-OBJ-00005H_y', 'DFL-OBJ-00005H_d', 'DFL-OBJ-00005H_s', 'DFL-OBJ-0027AY_x', 'DFL-OBJ-0027AY_y', 'DFL-OBJ-0027AY_d', 'DFL-OBJ-0027AY_s', 'DFL-OBJ-002GMV_x', 'DFL-OBJ-002GMV_y', 'DFL-OBJ-002GMV_d', 'DFL-OBJ-002GMV_s', 'DFL-OBJ-0025YM_x', 'DFL-OBJ-0025YM_y', 'DFL-OBJ-0025YM_d', 'DFL-OBJ-0025YM_s', 'DFL-OBJ-00003W_x', 'DFL-OBJ-00003W_y', 'DFL-OBJ-00003W_d', 'DFL-OBJ-00003W_s', 'DFL-OBJ-0000YE_x', 'DFL-OBJ-0000YE_y', 'DFL-OBJ-0000YE_d', 'DFL-OBJ-0000YE_s', 'DFL-OBJ-00021G_x', 'DFL-OBJ-00021G_y', 'DFL-OBJ-00021G_d', 'DFL-OBJ-00021G_s', 'DFL-OBJ-00265G_x', 'DFL-OBJ-00265G_y', 'DFL-OBJ-00265G_d', 'DFL-OBJ-00265G_s', 'DFL-OBJ-0001ZY_x', 'DFL-OBJ-0001ZY_y', 'DFL-OBJ-0001ZY_d', 'DFL-OBJ-0001ZY_s', 'DFL-OBJ-0002DT_x', 'DFL-OBJ-0002DT_y', 'DFL-OBJ-0002DT_d', 'DFL-OBJ-0002DT_s', 'DFL-OBJ-0026MI_x', 'DFL-OBJ-0026MI_y', 'DFL-OBJ-0026MI_d', 'DFL-OBJ-0026MI_s', 'DFL-OBJ-0026WW_x', 'DFL-OBJ-0026WW_y', 'DFL-OBJ-0026WW_d', 'DFL-OBJ-0026WW_s', 'DFL-OBJ-0028GO_x', 'DFL-OBJ-0028GO_y', 'DFL-OBJ-0028GO_d', 'DFL-OBJ-0028GO_s', 'DFL-OBJ-002GPN_x', 'DFL-OBJ-002GPN_y', 'DFL-OBJ-002GPN_d', 'DFL-OBJ-002GPN_s', 'DFL-OBJ-0000F9_x', 'DFL-OBJ-0000F9_y', 'DFL-OBJ-0000F9_d', 'DFL-OBJ-0000F9_s', 'DFL-OBJ-0028G2_x', 'DFL-OBJ-0028G2_y', 'DFL-OBJ-0028G2_d', 'DFL-OBJ-0028G2_s', 'DFL-OBJ-00017G_x', 'DFL-OBJ-00017G_y', 'DFL-OBJ-00017G_d', 'DFL-OBJ-00017G_s', 'DFL-OBJ-002GPI_x', 'DFL-OBJ-002GPI_y', 'DFL-OBJ-002GPI_d', 'DFL-OBJ-002GPI_s', 'DFL-OBJ-J01CVM_x', 'DFL-OBJ-J01CVM_y', 'DFL-OBJ-J01CVM_d', 'DFL-OBJ-J01CVM_s', 'DFL-OBJ-002G0F_x', 'DFL-OBJ-002G0F_y', 'DFL-OBJ-002G0F_d', 'DFL-OBJ-002G0F_s', 'next_timestamp', 'next_losing_team', 'next_gaining_team', 'next_gap_seconds', 'potential_regain']

Contoh:

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,DFL-OBJ-0000NZ_x,...,DFL-OBJ-J01CVM_s,DFL-OBJ-002G0F_x,DFL-OBJ-002G0F_y,DFL-OBJ-002G0F_d,DFL-OBJ-002G0F_s,next_timestamp,next_losing_team,next_gaining_team,next_gap_seconds,potential_regain
0,1,0 days 00:00:23.480000,10587,alive,DFL-CLU-00000G,0.480762,0.319118,0.37,22.85,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:00:42.840000,DFL-CLU-00000G,DFL-CLU-000008,19.36,False
1,1,0 days 00:00:42.840000,11071,alive,DFL-CLU-000008,0.709238,0.309706,0.21,14.81,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:00:49.520000,DFL-CLU-000008,DFL-CLU-00000G,6.68,False
2,1,0 days 00:00:49.520000,11238,alive,DFL-CLU-00000G,0.139524,0.496912,0.54,6.78,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:01:22.040000,DFL-CLU-00000G,DFL-CLU-000008,32.52,False
3,1,0 days 00:01:22.040000,12051,alive,DFL-CLU-000008,0.446857,0.982647,0.09,22.41,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:01:25.320000,DFL-CLU-000008,DFL-CLU-00000G,3.28,True
4,1,0 days 00:01:25.320000,12133,alive,DFL-CLU-00000G,0.341143,0.973529,0.12,24.30,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:01:32.760000,DFL-CLU-00000G,DFL-CLU-000008,7.44,False

In [54]:
# ==========================================
# FILTER POTENTIAL REGAIN
# ==========================================

regain_events = df[
    df["potential_regain"] == True
].copy()

regain_events = regain_events.reset_index(drop=True)

print("Jumlah potential regain:", len(regain_events))

display(
    regain_events.head(10)
)

# ==========================================
# EVENT ID
# ==========================================

regain_events.insert(
    0,
    "event_id",
    range(1, len(regain_events) + 1)
)

display(
    regain_events.head(10)
)

Jumlah potential regain: 1105

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,DFL-OBJ-0000NZ_x,...,DFL-OBJ-J01CVM_s,DFL-OBJ-002G0F_x,DFL-OBJ-002G0F_y,DFL-OBJ-002G0F_d,DFL-OBJ-002G0F_s,next_timestamp,next_losing_team,next_gaining_team,next_gap_seconds,potential_regain
0,1,0 days 00:01:22.040000,12051,alive,DFL-CLU-000008,0.446857,0.982647,0.09,22.41,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:01:25.320000,DFL-CLU-000008,DFL-CLU-00000G,3.28,True
1,1,0 days 00:02:09.760000,13244,alive,DFL-CLU-000008,0.350667,0.941618,0.20,41.53,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:02:14.680000,DFL-CLU-000008,DFL-CLU-00000G,4.92,True
2,1,0 days 00:02:23.560000,13589,alive,DFL-CLU-000008,0.328000,0.734706,0.26,45.06,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:02:25.160000,DFL-CLU-000008,DFL-CLU-00000G,1.60,True
3,1,0 days 00:02:25.160000,13629,alive,DFL-CLU-00000G,0.284476,0.773676,0.08,40.43,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:02:30.040000,DFL-CLU-00000G,DFL-CLU-000008,4.88,True
4,1,0 days 00:04:34.680000,16867,alive,DFL-CLU-000008,0.740190,0.188088,1.97,33.57,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:04:34.920000,DFL-CLU-000008,DFL-CLU-00000G,0.24,True
5,1,0 days 00:04:34.920000,16873,alive,DFL-CLU-00000G,0.758857,0.201029,1.11,35.11,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:04:36.600000,DFL-CLU-00000G,DFL-CLU-000008,1.68,True
6,1,0 days 00:05:04.880000,17622,alive,DFL-CLU-000008,0.839143,0.055294,0.16,15.58,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:05:06.040000,DFL-CLU-000008,DFL-CLU-00000G,1.16,True
7,1,0 days 00:05:36.680000,18417,alive,DFL-CLU-000008,0.610476,0.719412,0.02,43.66,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:05:40.040000,DFL-CLU-000008,DFL-CLU-00000G,3.36,True
8,1,0 days 00:05:52.680000,18817,alive,DFL-CLU-000008,0.571905,0.187353,0.11,10.38,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:05:53.680000,DFL-CLU-000008,DFL-CLU-00000G,1.00,True
9,1,0 days 00:06:01.680000,19042,alive,DFL-CLU-000008,0.705429,0.248529,0.06,25.34,NaN,...,NaN,NaN,NaN,NaN,NaN,0 days 00:06:02.240000,DFL-CLU-000008,DFL-CLU-00000G,0.56,True

,event_id,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,...,DFL-OBJ-J01CVM_s,DFL-OBJ-002G0F_x,DFL-OBJ-002G0F_y,DFL-OBJ-002G0F_d,DFL-OBJ-002G0F_s,next_timestamp,next_losing_team,next_gaining_team,next_gap_seconds,potential_regain
0,1,1,0 days 00:01:22.040000,12051,alive,DFL-CLU-000008,0.446857,0.982647,0.09,22.41,...,NaN,NaN,NaN,NaN,NaN,0 days 00:01:25.320000,DFL-CLU-000008,DFL-CLU-00000G,3.28,True
1,2,1,0 days 00:02:09.760000,13244,alive,DFL-CLU-000008,0.350667,0.941618,0.20,41.53,...,NaN,NaN,NaN,NaN,NaN,0 days 00:02:14.680000,DFL-CLU-000008,DFL-CLU-00000G,4.92,True
2,3,1,0 days 00:02:23.560000,13589,alive,DFL-CLU-000008,0.328000,0.734706,0.26,45.06,...,NaN,NaN,NaN,NaN,NaN,0 days 00:02:25.160000,DFL-CLU-000008,DFL-CLU-00000G,1.60,True
3,4,1,0 days 00:02:25.160000,13629,alive,DFL-CLU-00000G,0.284476,0.773676,0.08,40.43,...,NaN,NaN,NaN,NaN,NaN,0 days 00:02:30.040000,DFL-CLU-00000G,DFL-CLU-000008,4.88,True
4,5,1,0 days 00:04:34.680000,16867,alive,DFL-CLU-000008,0.740190,0.188088,1.97,33.57,...,NaN,NaN,NaN,NaN,NaN,0 days 00:04:34.920000,DFL-CLU-000008,DFL-CLU-00000G,0.24,True
5,6,1,0 days 00:04:34.920000,16873,alive,DFL-CLU-00000G,0.758857,0.201029,1.11,35.11,...,NaN,NaN,NaN,NaN,NaN,0 days 00:04:36.600000,DFL-CLU-00000G,DFL-CLU-000008,1.68,True
6,7,1,0 days 00:05:04.880000,17622,alive,DFL-CLU-000008,0.839143,0.055294,0.16,15.58,...,NaN,NaN,NaN,NaN,NaN,0 days 00:05:06.040000,DFL-CLU-000008,DFL-CLU-00000G,1.16,True
7,8,1,0 days 00:05:36.680000,18417,alive,DFL-CLU-000008,0.610476,0.719412,0.02,43.66,...,NaN,NaN,NaN,NaN,NaN,0 days 00:05:40.040000,DFL-CLU-000008,DFL-CLU-00000G,3.36,True
8,9,1,0 days 00:05:52.680000,18817,alive,DFL-CLU-000008,0.571905,0.187353,0.11,10.38,...,NaN,NaN,NaN,NaN,NaN,0 days 00:05:53.680000,DFL-CLU-000008,DFL-CLU-00000G,1.00,True
9,10,1,0 days 00:06:01.680000,19042,alive,DFL-CLU-000008,0.705429,0.248529,0.06,25.34,...,NaN,NaN,NaN,NaN,NaN,0 days 00:06:02.240000,DFL-CLU-000008,DFL-CLU-00000G,0.56,True

In [55]:
# ==========================================
# DISTRIBUSI POTENTIAL REGAIN
# ==========================================

regain_distribution = (
    regain_events
    .groupby("match_id")
    .size()
    .reset_index(name="potential_regain_count")
    .sort_values("match_id")
)

display(regain_distribution)
print(
    "Total:",
    regain_distribution["potential_regain_count"].sum()
)

  match_id  potential_regain_count
0   J03WMX                     211
1   J03WN1                     204
2   J03WOH                     138
3   J03WOY                     171
4   J03WPY                     148
5   J03WQQ                     121
6   J03WR9                     112

Total: 1105

CEK DISTRIBUSI BERDASARKAN TIM

In [56]:
# ==========================================
# MEMBENTUK ULANG POTENTIAL REGAIN EVENTS
# ==========================================

# Pastikan df memang memiliki kolom yang dibutuhkan
required_columns = [
    "match_id",
    "period_id",
    "timestamp",
    "frame_id",
    "prev_owning_team",
    "ball_owning_team_id",
    "next_timestamp",
    "next_gap_seconds",
    "next_gaining_team",
    "potential_regain"
]

missing = [
    col for col in required_columns
    if col not in df.columns
]

if missing:
    raise ValueError(
        f"Kolom berikut belum tersedia di df: {missing}"
    )


# Ambil hanya baris yang memenuhi potential regain
regain_events = df[
    df["potential_regain"] == True
].copy()

regain_events = regain_events.reset_index(drop=True)


# ==========================================
# BUAT EVENT ID
# ==========================================

regain_events["event_id"] = (
    regain_events.index + 1
)


# ==========================================
# DEFINISI TIM
# ==========================================

# Tim yang kehilangan bola pada T0
regain_events["losing_team"] = (
    regain_events["prev_owning_team"]
)

# Tim yang mendapatkan bola setelah kehilangan
regain_events["opponent_team"] = (
    regain_events["ball_owning_team_id"]
)

# Karena potential_regain == True,
# candidate berikutnya mendapatkan bola kembali
# kepada tim yang sebelumnya kehilangan bola.
regain_events["regain_team"] = (
    regain_events["next_gaining_team"]
)


# ==========================================
# WAKTU REGAIN
# ==========================================

regain_events["regain_timestamp"] = (
    regain_events["next_timestamp"]
)

regain_events["regain_gap_seconds"] = (
    regain_events["next_gap_seconds"]
)


# ==========================================
# CEK HASIL
# ==========================================

print(
    "Jumlah potential regain:",
    len(regain_events)
)

print("\nKolom penting:")
print([
    "event_id",
    "match_id",
    "period_id",
    "timestamp",
    "losing_team",
    "opponent_team",
    "regain_team",
    "regain_timestamp",
    "regain_gap_seconds"
])


display(
    regain_events[
        [
            "event_id",
            "match_id",
            "period_id",
            "timestamp",
            "losing_team",
            "opponent_team",
            "regain_team",
            "regain_timestamp",
            "regain_gap_seconds"
        ]
    ].head(20)
)

Jumlah potential regain: 1105

Kolom penting:
['event_id', 'match_id', 'period_id', 'timestamp', 'losing_team', 'opponent_team', 'regain_team', 'regain_timestamp', 'regain_gap_seconds']

,event_id,match_id,period_id,timestamp,losing_team,opponent_team,regain_team,regain_timestamp,regain_gap_seconds
0,1,J03WMX,1,0 days 00:01:22.040000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:01:25.320000,3.28
1,2,J03WMX,1,0 days 00:02:09.760000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:02:14.680000,4.92
2,3,J03WMX,1,0 days 00:02:23.560000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:02:25.160000,1.60
3,4,J03WMX,1,0 days 00:02:25.160000,DFL-CLU-000008,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:02:30.040000,4.88
4,5,J03WMX,1,0 days 00:04:34.680000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:04:34.920000,0.24
5,6,J03WMX,1,0 days 00:04:34.920000,DFL-CLU-000008,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:04:36.600000,1.68
6,7,J03WMX,1,0 days 00:05:04.880000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:05:06.040000,1.16
7,8,J03WMX,1,0 days 00:05:36.680000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:05:40.040000,3.36
8,9,J03WMX,1,0 days 00:05:52.680000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:05:53.680000,1.00
9,10,J03WMX,1,0 days 00:06:01.680000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:02.240000,0.56
10,11,J03WMX,1,0 days 00:06:02.240000,DFL-CLU-000008,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:03.360000,1.12
11,12,J03WMX,1,0 days 00:06:03.360000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:04.920000,1.56
12,13,J03WMX,1,0 days 00:06:10.040000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:11.040000,1.00
13,14,J03WMX,1,0 days 00:06:11.040000,DFL-CLU-000008,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:11.200000,0.16
14,15,J03WMX,1,0 days 00:06:11.200000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:11.840000,0.64
15,16,J03WMX,1,0 days 00:06:53.800000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:55.080000,1.28
16,17,J03WMX,1,0 days 00:06:55.080000,DFL-CLU-000008,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:56,0.92
17,18,J03WMX,1,0 days 00:07:39.560000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:07:40.560000,1.00
18,19,J03WMX,1,0 days 00:08:43.560000,DFL-CLU-000008,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:08:44.600000,1.04
19,20,J03WMX,1,0 days 00:08:44.600000,DFL-CLU-00000G,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:08:48.880000,4.28

In [57]:
# ==========================================
# DISTRIBUSI REGAIN PER TIM
# ==========================================

team_regain = (
    regain_events
    .groupby("regain_team")
    .size()
    .reset_index(name="regain_count")
    .sort_values(
        "regain_count",
        ascending=False
    )
)

display(team_regain)

print(
    "Total potential regain:",
    team_regain["regain_count"].sum()
)

match_regain = (
    regain_events
    .groupby("match_id")
    .size()
    .reset_index(name="potential_regain_count")
    .sort_values("match_id")
)

display(match_regain)

print(
    "Total:",
    match_regain["potential_regain_count"].sum()
)

print(
    regain_events["regain_gap_seconds"].describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)

      regain_team  regain_count
6  DFL-CLU-00000P           351
3  DFL-CLU-00000G           106
2  DFL-CLU-00000B           105
1  DFL-CLU-000008           105
8  DFL-CLU-00000S            99
7  DFL-CLU-00000Q            83
4  DFL-CLU-00000H            73
9  DFL-CLU-000011            69
0  DFL-CLU-000005            66
5  DFL-CLU-00000I            48

Total potential regain: 1105

  match_id  potential_regain_count
0   J03WMX                     211
1   J03WN1                     204
2   J03WOH                     138
3   J03WOY                     171
4   J03WPY                     148
5   J03WQQ                     121
6   J03WR9                     112

Total: 1105
count    1105.000000
mean        2.251439
std         1.326487
min         0.040000
25%         1.240000
50%         2.080000
75%         3.280000
90%         4.280000
95%         4.640000
max         5.000000
Name: regain_gap_seconds, dtype: float64

In [58]:
# ==========================================
# POTENTIAL REGAIN DALAM 5 DETIK
# VERSI YANG DIKOREKSI
# ==========================================

base = all_candidates_df.copy()

# Urutkan
base = base.sort_values(
    ["match_id", "period_id", "timestamp"]
).reset_index(drop=True)

# Kolom hasil
base["regain_found"] = False
base["regain_timestamp"] = pd.NaT
base["regain_gap_seconds"] = pd.NA
base["regain_from_team"] = pd.NA


# ==========================================
# CARI REGAIN DALAM WINDOW 5 DETIK
# ==========================================

for (match_id, period_id), group in base.groupby(
    ["match_id", "period_id"],
    sort=False
):

    idx = group.index.to_numpy()
    owners = group["ball_owning_team_id"].to_numpy()
    losing_teams = group["prev_owning_team"].to_numpy()

    for i in range(len(group)):

        t0 = group["timestamp"].iloc[i]
        losing_team = losing_teams[i]

        if pd.isna(losing_team):
            continue

        # Batas waktu regain
        end_time = t0 + pd.Timedelta(seconds=5)

        # Cari candidate berikutnya sampai 5 detik
        for j in range(i + 1, len(group)):

            t1 = group["timestamp"].iloc[j]

            if t1 > end_time:
                break

            # Apakah bola kembali ke losing team?
            if owners[j] == losing_team:

                row_idx = idx[i]

                base.loc[
                    row_idx,
                    "regain_found"
                ] = True

                base.loc[
                    row_idx,
                    "regain_timestamp"
                ] = t1

                base.loc[
                    row_idx,
                    "regain_gap_seconds"
                ] = (t1 - t0).total_seconds()

                base.loc[
                    row_idx,
                    "regain_from_team"
                ] = owners[j - 1]

                # ambil regain pertama
                break


# ==========================================
# AMBIL POTENTIAL REGAIN
# ==========================================

regain_events_corrected = base[
    base["regain_found"] == True
].copy()

regain_events_corrected = (
    regain_events_corrected.reset_index(drop=True)
)

regain_events_corrected["event_id"] = (
    regain_events_corrected.index + 1
)


# ==========================================
# INFORMASI TIM
# ==========================================

regain_events_corrected["losing_team"] = (
    regain_events_corrected["prev_owning_team"]
)

regain_events_corrected["opponent_team"] = (
    regain_events_corrected["ball_owning_team_id"]
)


# ==========================================
# HASIL
# ==========================================

print(
    "Total candidate:",
    len(base)
)

print(
    "Potential regain ≤5 detik:",
    len(regain_events_corrected)
)

print(
    "Persentase:",
    round(
        len(regain_events_corrected)
        / len(base)
        * 100,
        2
    ),
    "%"
)

C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:62: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0 days 00:01:25.320000' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  base.loc[
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.

Total candidate: 2353
Potential regain ≤5 detik: 1105
Persentase: 46.96 %

C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  end_time = t0 + pd.Timedelta(seconds=5)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2469902624.py:42: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.

In [59]:
print(
    regain_events_corrected[
        "regain_gap_seconds"
    ].describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95
        ]
    )
)
print(
    "\nDistribusi per pertandingan:"
)

display(
    regain_events_corrected
    .groupby("match_id")
    .size()
    .reset_index(
        name="potential_regain_count"
    )
)
display(
    regain_events_corrected[
        [
            "event_id",
            "match_id",
            "period_id",
            "timestamp",
            "losing_team",
            "opponent_team",
            "regain_timestamp",
            "regain_from_team",
            "regain_gap_seconds"
        ]
    ].head(20)
)

count     1105.00
unique     125.00
top          0.16
freq        26.00
Name: regain_gap_seconds, dtype: float64

Distribusi per pertandingan:

  match_id  potential_regain_count
0   J03WMX                     211
1   J03WN1                     204
2   J03WOH                     138
3   J03WOY                     171
4   J03WPY                     148
5   J03WQQ                     121
6   J03WR9                     112

,event_id,match_id,period_id,timestamp,losing_team,opponent_team,regain_timestamp,regain_from_team,regain_gap_seconds
0,1,J03WMX,1,0 days 00:01:22.040000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:01:25.320000,DFL-CLU-000008,3.28
1,2,J03WMX,1,0 days 00:02:09.760000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:02:14.680000,DFL-CLU-000008,4.92
2,3,J03WMX,1,0 days 00:02:23.560000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:02:25.160000,DFL-CLU-000008,1.6
3,4,J03WMX,1,0 days 00:02:25.160000,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:02:30.040000,DFL-CLU-00000G,4.88
4,5,J03WMX,1,0 days 00:04:34.680000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:04:34.920000,DFL-CLU-000008,0.24
5,6,J03WMX,1,0 days 00:04:34.920000,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:04:36.600000,DFL-CLU-00000G,1.68
6,7,J03WMX,1,0 days 00:05:04.880000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:05:06.040000,DFL-CLU-000008,1.16
7,8,J03WMX,1,0 days 00:05:36.680000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:05:40.040000,DFL-CLU-000008,3.36
8,9,J03WMX,1,0 days 00:05:52.680000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:05:53.680000,DFL-CLU-000008,1.0
9,10,J03WMX,1,0 days 00:06:01.680000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:02.240000,DFL-CLU-000008,0.56
10,11,J03WMX,1,0 days 00:06:02.240000,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:03.360000,DFL-CLU-00000G,1.12
11,12,J03WMX,1,0 days 00:06:03.360000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:04.920000,DFL-CLU-000008,1.56
12,13,J03WMX,1,0 days 00:06:10.040000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:11.040000,DFL-CLU-000008,1.0
13,14,J03WMX,1,0 days 00:06:11.040000,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:11.200000,DFL-CLU-00000G,0.16
14,15,J03WMX,1,0 days 00:06:11.200000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:11.840000,DFL-CLU-000008,0.64
15,16,J03WMX,1,0 days 00:06:53.800000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:06:55.080000,DFL-CLU-000008,1.28
16,17,J03WMX,1,0 days 00:06:55.080000,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:06:56,DFL-CLU-00000G,0.92
17,18,J03WMX,1,0 days 00:07:39.560000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:07:40.560000,DFL-CLU-000008,1.0
18,19,J03WMX,1,0 days 00:08:43.560000,DFL-CLU-000008,DFL-CLU-00000G,0 days 00:08:44.600000,DFL-CLU-00000G,1.04
19,20,J03WMX,1,0 days 00:08:44.600000,DFL-CLU-00000G,DFL-CLU-000008,0 days 00:08:48.880000,DFL-CLU-000008,4.28

In [60]:
# ==========================================
# AMBIL 1 EPISODE POTENTIAL REGAIN
# ==========================================

episode = regain_events_corrected[
    regain_events_corrected["event_id"] == 1
].iloc[0]

print("=== EPISODE 1 ===")
print("Match        :", episode["match_id"])
print("Period       :", episode["period_id"])
print("Loss time    :", episode["timestamp"])
print("Losing team  :", episode["losing_team"])
print("Opponent     :", episode["opponent_team"])
print("Regain time  :", episode["regain_timestamp"])
print("Regain gap   :", episode["regain_gap_seconds"], "detik")

# ==========================================
# LOAD TRACKING EPISODE
# ==========================================

match_id = episode["match_id"]

tracking_path = DATA_DIR / f"{match_id}_tracking.csv"

episode_tracking = pd.read_csv(tracking_path)

episode_tracking["timestamp"] = pd.to_timedelta(
    episode_tracking["timestamp"],
    errors="coerce"
)

episode_tracking = episode_tracking.sort_values(
    ["period_id", "timestamp", "frame_id"]
).reset_index(drop=True)

print("Tracking shape:", episode_tracking.shape)

# ==========================================
# EPISODE TRACKING WINDOW
# ==========================================

t0 = episode["timestamp"]
t1 = episode["regain_timestamp"]
period_id = episode["period_id"]

window_start = t0 - pd.Timedelta(seconds=2)
window_end = t1 + pd.Timedelta(seconds=1)

episode_window = episode_tracking[
    (episode_tracking["period_id"] == period_id)
    & (episode_tracking["timestamp"] >= window_start)
    & (episode_tracking["timestamp"] <= window_end)
].copy()

print("=== EPISODE WINDOW ===")
print("Mulai :", window_start)
print("Loss  :", t0)
print("Regain :", t1)
print("Selesai:", window_end)
print("Jumlah frame:", len(episode_window))

display(
    episode_window[
        [
            "timestamp",
            "frame_id",
            "ball_state",
            "ball_owning_team_id",
            "ball_x",
            "ball_y"
        ]
    ].iloc[
        max(0, len(episode_window)//2 - 10):
        min(len(episode_window), len(episode_window)//2 + 10)
    ]
)

# ==========================================
# SEKITAR LOSS
# ==========================================

loss_context = episode_window[
    (episode_window["timestamp"] >= t0 - pd.Timedelta(seconds=0.5))
    & (episode_window["timestamp"] <= t0 + pd.Timedelta(seconds=0.5))
]

display(
    loss_context[
        [
            "timestamp",
            "frame_id",
            "ball_state",
            "ball_owning_team_id",
            "ball_x",
            "ball_y"
        ]
    ]
)

# ==========================================
# SEKITAR REGAIN
# ==========================================

regain_context = episode_window[
    (episode_window["timestamp"] >= t1 - pd.Timedelta(seconds=0.5))
    & (episode_window["timestamp"] <= t1 + pd.Timedelta(seconds=0.5))
]

display(
    regain_context[
        [
            "timestamp",
            "frame_id",
            "ball_state",
            "ball_owning_team_id",
            "ball_x",
            "ball_y"
        ]
    ]
)

# ==========================================
# FRAME TERDEKAT DENGAN LOSS
# ==========================================

loss_row = episode_tracking[
    episode_tracking["period_id"] == period_id
].copy()

loss_row["time_diff"] = (
    loss_row["timestamp"] - t0
).abs()

loss_row = loss_row.sort_values("time_diff").iloc[0]

print("Loss target :", t0)
print("Frame loss  :", loss_row["frame_id"])
print("Timestamp   :", loss_row["timestamp"])
print("Selisih     :", loss_row["time_diff"])

# ==========================================
# FRAME TERDEKAT DENGAN REGAIN
# ==========================================

regain_row = episode_tracking[
    episode_tracking["period_id"] == period_id
].copy()

regain_row["time_diff"] = (
    regain_row["timestamp"] - t1
).abs()

regain_row = regain_row.sort_values(
    "time_diff"
).iloc[0]

print("Regain target:", t1)
print("Frame regain :", regain_row["frame_id"])
print("Timestamp    :", regain_row["timestamp"])
print("Selisih      :", regain_row["time_diff"])

=== EPISODE 1 ===
Match        : J03WMX
Period       : 1
Loss time    : 0 days 00:01:22.040000
Losing team  : DFL-CLU-00000G
Opponent     : DFL-CLU-000008
Regain time  : 0 days 00:01:25.320000
Regain gap   : 3.2800000000000002 detik
Tracking shape: (145967, 137)
=== EPISODE WINDOW ===
Mulai : 0 days 00:01:20.040000
Loss  : 0 days 00:01:22.040000
Regain : 0 days 00:01:25.320000
Selesai: 0 days 00:01:26.320000
Jumlah frame: 158

C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2383567007.py:47: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  window_start = t0 - pd.Timedelta(seconds=2)
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2383567007.py:48: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  window_end = t1 + pd.Timedelta(seconds=1)

,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y
2070,0 days 00:01:22.800000,12070,alive,DFL-CLU-000008,0.495905,0.982941
2071,0 days 00:01:22.840000,12071,alive,DFL-CLU-000008,0.497714,0.982647
2072,0 days 00:01:22.880000,12072,alive,DFL-CLU-000008,0.499619,0.982647
2073,0 days 00:01:22.920000,12073,alive,DFL-CLU-000008,0.501524,0.982353
2074,0 days 00:01:22.960000,12074,alive,DFL-CLU-000008,0.503429,0.982059
2075,0 days 00:01:23,12075,alive,DFL-CLU-000008,0.505143,0.981324
2076,0 days 00:01:23.040000,12076,alive,DFL-CLU-000008,0.506952,0.981324
2077,0 days 00:01:23.080000,12077,alive,DFL-CLU-000008,0.508762,0.981029
2078,0 days 00:01:23.120000,12078,alive,DFL-CLU-000008,0.510667,0.981029
2079,0 days 00:01:23.160000,12079,alive,DFL-CLU-000008,0.512381,0.980441
2080,0 days 00:01:23.200000,12080,alive,DFL-CLU-000008,0.513429,0.980735
2081,0 days 00:01:23.240000,12081,alive,DFL-CLU-000008,0.514571,0.980441
2082,0 days 00:01:23.280000,12082,alive,DFL-CLU-000008,0.515714,0.980294
2083,0 days 00:01:23.320000,12083,alive,DFL-CLU-000008,0.516762,0.980294
2084,0 days 00:01:23.360000,12084,alive,DFL-CLU-000008,0.518000,0.980000
2085,0 days 00:01:23.400000,12085,alive,DFL-CLU-000008,0.520381,0.979118
2086,0 days 00:01:23.440000,12086,alive,DFL-CLU-000008,0.525333,0.977206
2087,0 days 00:01:23.480000,12087,alive,DFL-CLU-000008,0.526190,0.976471
2088,0 days 00:01:23.520000,12088,alive,DFL-CLU-000008,0.529238,0.975441
2089,0 days 00:01:23.560000,12089,alive,DFL-CLU-000008,0.515333,0.978676

C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2383567007.py:84: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  (episode_window["timestamp"] >= t0 - pd.Timedelta(seconds=0.5))
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2383567007.py:85: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  & (episode_window["timestamp"] <= t0 + pd.Timedelta(seconds=0.5))

,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y
2039,0 days 00:01:21.560000,12039,alive,DFL-CLU-00000G,0.437143,0.991176
2040,0 days 00:01:21.600000,12040,alive,DFL-CLU-00000G,0.437810,0.991176
2041,0 days 00:01:21.640000,12041,alive,DFL-CLU-00000G,0.437619,0.991176
2042,0 days 00:01:21.680000,12042,alive,DFL-CLU-00000G,0.438381,0.991176
2043,0 days 00:01:21.720000,12043,alive,DFL-CLU-00000G,0.438190,0.991176
2044,0 days 00:01:21.760000,12044,alive,DFL-CLU-00000G,0.438381,0.991176
2045,0 days 00:01:21.800000,12045,alive,DFL-CLU-00000G,0.438571,0.991176
2046,0 days 00:01:21.840000,12046,alive,DFL-CLU-00000G,0.438857,0.991176
2047,0 days 00:01:21.880000,12047,alive,DFL-CLU-00000G,0.439429,0.991176
2048,0 days 00:01:21.920000,12048,alive,DFL-CLU-00000G,0.440000,0.991324
2049,0 days 00:01:21.960000,12049,alive,DFL-CLU-00000G,0.441143,0.982941
2050,0 days 00:01:22,12050,alive,DFL-CLU-00000G,0.443905,0.982647
2051,0 days 00:01:22.040000,12051,alive,DFL-CLU-000008,0.446857,0.982647
2052,0 days 00:01:22.080000,12052,alive,DFL-CLU-000008,0.449429,0.982059
2053,0 days 00:01:22.120000,12053,alive,DFL-CLU-000008,0.453905,0.985735
2054,0 days 00:01:22.160000,12054,alive,DFL-CLU-000008,0.456476,0.985882
2055,0 days 00:01:22.200000,12055,alive,DFL-CLU-000008,0.459238,0.985882
2056,0 days 00:01:22.240000,12056,alive,DFL-CLU-000008,0.461905,0.985588
2057,0 days 00:01:22.280000,12057,alive,DFL-CLU-000008,0.464667,0.985588
2058,0 days 00:01:22.320000,12058,alive,DFL-CLU-000008,0.467429,0.985441
2059,0 days 00:01:22.360000,12059,alive,DFL-CLU-000008,0.470095,0.984853
2060,0 days 00:01:22.400000,12060,alive,DFL-CLU-000008,0.472762,0.985147
2061,0 days 00:01:22.440000,12061,alive,DFL-CLU-000008,0.475333,0.984706
2062,0 days 00:01:22.480000,12062,alive,DFL-CLU-000008,0.478095,0.984559
2063,0 days 00:01:22.520000,12063,alive,DFL-CLU-000008,0.480857,0.984412

C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2383567007.py:106: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  (episode_window["timestamp"] >= t1 - pd.Timedelta(seconds=0.5))
C:\Users\rizal\AppData\Local\Temp\ipykernel_2544\2383567007.py:107: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  & (episode_window["timestamp"] <= t1 + pd.Timedelta(seconds=0.5))

,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y
2121,0 days 00:01:24.840000,12121,alive,DFL-CLU-000008,0.373810,0.979265
2122,0 days 00:01:24.880000,12122,alive,DFL-CLU-000008,0.370571,0.978971
2123,0 days 00:01:24.920000,12123,alive,DFL-CLU-000008,0.367429,0.978824
2124,0 days 00:01:24.960000,12124,alive,DFL-CLU-000008,0.364095,0.978382
2125,0 days 00:01:25,12125,alive,DFL-CLU-000008,0.360952,0.977647
2126,0 days 00:01:25.040000,12126,alive,DFL-CLU-000008,0.357905,0.977206
2127,0 days 00:01:25.080000,12127,alive,DFL-CLU-000008,0.355143,0.976765
2128,0 days 00:01:25.120000,12128,alive,DFL-CLU-000008,0.352762,0.976324
2129,0 days 00:01:25.160000,12129,alive,DFL-CLU-000008,0.350286,0.975882
2130,0 days 00:01:25.200000,12130,alive,DFL-CLU-000008,0.348000,0.975441
2131,0 days 00:01:25.240000,12131,alive,DFL-CLU-000008,0.346190,0.976176
2132,0 days 00:01:25.280000,12132,alive,DFL-CLU-000008,0.342952,0.972941
2133,0 days 00:01:25.320000,12133,alive,DFL-CLU-00000G,0.341143,0.973529
2134,0 days 00:01:25.360000,12134,alive,DFL-CLU-00000G,0.339619,0.975000
2135,0 days 00:01:25.400000,12135,alive,DFL-CLU-00000G,0.338857,0.976029
2136,0 days 00:01:25.440000,12136,alive,DFL-CLU-00000G,0.338762,0.975441
2137,0 days 00:01:25.480000,12137,alive,DFL-CLU-00000G,0.338952,0.975882
2138,0 days 00:01:25.520000,12138,alive,DFL-CLU-00000G,0.339143,0.976618
2139,0 days 00:01:25.560000,12139,alive,DFL-CLU-00000G,0.338667,0.976471
2140,0 days 00:01:25.600000,12140,alive,DFL-CLU-00000G,0.338476,0.977059
2141,0 days 00:01:25.640000,12141,alive,DFL-CLU-00000G,0.337810,0.976912
2142,0 days 00:01:25.680000,12142,alive,DFL-CLU-00000G,0.337429,0.976765
2143,0 days 00:01:25.720000,12143,alive,DFL-CLU-00000G,0.337333,0.977206
2144,0 days 00:01:25.760000,12144,alive,DFL-CLU-00000G,0.337048,0.977794
2145,0 days 00:01:25.800000,12145,alive,DFL-CLU-00000G,0.336286,0.977500

Loss target : 0 days 00:01:22.040000
Frame loss  : 12051
Timestamp   : 0 days 00:01:22.040000
Selisih     : 0 days 00:00:00
Regain target: 0 days 00:01:25.320000
Frame regain : 12133
Timestamp    : 0 days 00:01:25.320000
Selisih      : 0 days 00:00:00

LANGKAH KE 2

In [64]:
# ==========================================
# LOAD EVENT KHUSUS MATCH EPISODE
# ==========================================
print("Match:", episode["match_id"])
print("Period:", episode["period_id"])
print("Loss:", episode["timestamp"])
print("Regain:", episode["regain_timestamp"])


match_id = episode["match_id"]

events_path = DATA_DIR / f"{match_id}_events.csv"

events_episode = pd.read_csv(events_path)

events_episode["timestamp"] = pd.to_timedelta(
    events_episode["timestamp"],
    errors="coerce"
)

print("Event shape:", events_episode.shape)
print("Match:", match_id)

# ==========================================
# PLAYER → TEAM MAPPING
# ==========================================

player_team_episode = (
    events_episode[
        ["player_id", "team_id"]
    ]
    .dropna()
    .drop_duplicates()
)

print(
    "Jumlah player-team mapping:",
    len(player_team_episode)
)

display(
    player_team_episode.head(20)
)

# ==========================================
# IDENTIFIKASI PLAYER DARI KOLOM TRACKING
# ==========================================

player_ids_tracking = sorted({
    col[:-2]
    for col in episode_tracking.columns
    if (
        col.startswith("DFL-OBJ-")
        and col.endswith("_x")
    )
})

print(
    "Jumlah player/object dari tracking:",
    len(player_ids_tracking)
)

for player_id in player_ids_tracking:
    print(player_id)
    
# ==========================================
# PEMAIN PADA SAAT LOSS
# ==========================================

loss_nodes = []

for player_id in player_ids_tracking:

    x_col = f"{player_id}_x"
    y_col = f"{player_id}_y"
    s_col = f"{player_id}_s"

    # Pastikan kolom tersedia
    if (
        x_col not in episode_tracking.columns
        or y_col not in episode_tracking.columns
    ):
        continue

    x = frame_loss[x_col]
    y = frame_loss[y_col]

    # Hanya pemain dengan posisi valid
    if pd.isna(x) or pd.isna(y):
        continue

    # Cari team pemain
    team_rows = player_team_episode[
        player_team_episode["player_id"] == player_id
    ]

    if len(team_rows) == 0:
        continue

    team_id = team_rows["team_id"].iloc[0]

    speed = frame_loss[s_col]

    loss_nodes.append({
        "player_id": player_id,
        "team_id": team_id,
        "x": x,
        "y": y,
        "speed": speed
    })

loss_nodes_df = pd.DataFrame(loss_nodes)

print(
    "Jumlah pemain aktif saat LOSS:",
    len(loss_nodes_df)
)

display(loss_nodes_df)

ball_x = frame_loss["ball_x"]
ball_y = frame_loss["ball_y"]

print("Ball X:", ball_x)
print("Ball Y:", ball_y)

# ==========================================
# DISTANCE PLAYER → BALL
# ==========================================

loss_nodes_df["distance_to_ball"] = (
    (
        (loss_nodes_df["x"] - ball_x) ** 2
        +
        (loss_nodes_df["y"] - ball_y) ** 2
    ) ** 0.5
)

loss_nodes_df = loss_nodes_df.sort_values(
    "distance_to_ball"
).reset_index(drop=True)

display(loss_nodes_df)

losing_team = episode["losing_team"]

losing_players = loss_nodes_df[
    loss_nodes_df["team_id"] == losing_team
].copy()

losing_players = losing_players.sort_values(
    "distance_to_ball"
)

print(
    "Jumlah pemain tim yang kehilangan bola:",
    len(losing_players)
)

display(losing_players)

Match: J03WMX
Period: 1
Loss: 0 days 00:01:22.040000
Regain: 0 days 00:01:25.320000
Event shape: (1789, 19)
Match: J03WMX
Jumlah player-team mapping: 32

         player_id         team_id
0   DFL-OBJ-0027G6  DFL-CLU-00000G
1   DFL-OBJ-0027KL  DFL-CLU-00000G
3   DFL-OBJ-0002BO  DFL-CLU-000008
6   DFL-OBJ-J01B8N  DFL-CLU-00000G
8   DFL-OBJ-0002AU  DFL-CLU-00000G
9   DFL-OBJ-0027G0  DFL-CLU-00000G
11  DFL-OBJ-J017RE  DFL-CLU-00000G
13  DFL-OBJ-0026PM  DFL-CLU-00000G
14  DFL-OBJ-0027B6  DFL-CLU-000008
15  DFL-OBJ-0002DR  DFL-CLU-00000G
19  DFL-OBJ-0002F5  DFL-CLU-00000G
30  DFL-OBJ-J01D1W  DFL-CLU-000008
34  DFL-OBJ-002GKO  DFL-CLU-000008
35  DFL-OBJ-J01BGM  DFL-CLU-000008
36  DFL-OBJ-0027AX  DFL-CLU-000008
46  DFL-OBJ-00012X  DFL-CLU-000008
54  DFL-OBJ-002G4A  DFL-CLU-000008
68  DFL-OBJ-J01APO  DFL-CLU-00000G
75  DFL-OBJ-0028BD  DFL-CLU-000008
90  DFL-OBJ-0002HE  DFL-CLU-000008

Jumlah player/object dari tracking: 32
DFL-OBJ-0000IA
DFL-OBJ-0000RP
DFL-OBJ-00012X
DFL-OBJ-000191
DFL-OBJ-000270
DFL-OBJ-0002AU
DFL-OBJ-0002BO
DFL-OBJ-0002DR
DFL-OBJ-0002F5
DFL-OBJ-0002HE
DFL-OBJ-0026PM
DFL-OBJ-0026ZI
DFL-OBJ-0027AX
DFL-OBJ-0027B6
DFL-OBJ-0027G0
DFL-OBJ-0027G6
DFL-OBJ-0027KL
DFL-OBJ-0027V2
DFL-OBJ-0028BD
DFL-OBJ-002G4A
DFL-OBJ-002G89
DFL-OBJ-002GBW
DFL-OBJ-002GCR
DFL-OBJ-002GKO
DFL-OBJ-J015S4
DFL-OBJ-J017RE
DFL-OBJ-J01APO
DFL-OBJ-J01B8N
DFL-OBJ-J01BGM
DFL-OBJ-J01D1W
DFL-OBJ-J01DVC
DFL-OBJ-J01N65
Jumlah pemain aktif saat LOSS: 22

         player_id         team_id         x         y  speed
0   DFL-OBJ-0000IA  DFL-CLU-00000G  0.542095  0.883382   4.87
1   DFL-OBJ-00012X  DFL-CLU-000008  0.445048  0.976471   8.45
2   DFL-OBJ-000270  DFL-CLU-000008  0.444857  0.639265   5.08
3   DFL-OBJ-0002AU  DFL-CLU-00000G  0.443048  0.992941   8.73
4   DFL-OBJ-0002BO  DFL-CLU-000008  0.598286  0.266324   6.41
5   DFL-OBJ-0002DR  DFL-CLU-00000G  0.137905  0.580735   2.81
6   DFL-OBJ-0002F5  DFL-CLU-00000G  0.324000  0.633382   5.78
7   DFL-OBJ-0002HE  DFL-CLU-000008  0.854286  0.570441   4.44
8   DFL-OBJ-0026PM  DFL-CLU-00000G  0.610762  0.082794   3.92
9   DFL-OBJ-0027AX  DFL-CLU-000008  0.360952  0.727647  10.49
10  DFL-OBJ-0027B6  DFL-CLU-000008  0.605524  0.596912   6.58
11  DFL-OBJ-0027G0  DFL-CLU-00000G  0.416571  0.837206   7.75
12  DFL-OBJ-0027G6  DFL-CLU-00000G  0.517048  0.417059   0.28
13  DFL-OBJ-0027KL  DFL-CLU-00000G  0.286952  0.910294   9.15
14  DFL-OBJ-0028BD  DFL-CLU-000008  0.402095  0.938971  12.54
15  DFL-OBJ-002G4A  DFL-CLU-000008  0.463905  0.841912   8.92
16  DFL-OBJ-002GKO  DFL-CLU-000008  0.529714  0.650294   8.36
17  DFL-OBJ-J017RE  DFL-CLU-00000G  0.282476  0.443529   5.42
18  DFL-OBJ-J01APO  DFL-CLU-00000G  0.377143  0.198088   8.87
19  DFL-OBJ-J01B8N  DFL-CLU-00000G  0.454667  0.622941   4.06
20  DFL-OBJ-J01BGM  DFL-CLU-000008  0.392190  0.461912   6.13
21  DFL-OBJ-J01D1W  DFL-CLU-000008  0.564952  0.891912  15.60

Ball X: 0.4468571428571428
Ball Y: 0.9826470588235292

,player_id,team_id,x,y,speed,distance_to_ball
0,DFL-OBJ-00012X,DFL-CLU-000008,0.445048,0.976471,8.45,0.006436
1,DFL-OBJ-0002AU,DFL-CLU-00000G,0.443048,0.992941,8.73,0.010976
2,DFL-OBJ-0028BD,DFL-CLU-000008,0.402095,0.938971,12.54,0.062540
3,DFL-OBJ-0000IA,DFL-CLU-00000G,0.542095,0.883382,4.87,0.137564
4,DFL-OBJ-002G4A,DFL-CLU-000008,0.463905,0.841912,8.92,0.141764
5,DFL-OBJ-0027G0,DFL-CLU-00000G,0.416571,0.837206,7.75,0.148561
6,DFL-OBJ-J01D1W,DFL-CLU-000008,0.564952,0.891912,15.60,0.148927
7,DFL-OBJ-0027KL,DFL-CLU-00000G,0.286952,0.910294,9.15,0.175512
8,DFL-OBJ-0027AX,DFL-CLU-000008,0.360952,0.727647,10.49,0.269081
9,DFL-OBJ-002GKO,DFL-CLU-000008,0.529714,0.650294,8.36,0.342526
10,DFL-OBJ-000270,DFL-CLU-000008,0.444857,0.639265,5.08,0.343388
11,DFL-OBJ-J01B8N,DFL-CLU-00000G,0.454667,0.622941,4.06,0.359791
12,DFL-OBJ-0002F5,DFL-CLU-00000G,0.324000,0.633382,5.78,0.370243
13,DFL-OBJ-0027B6,DFL-CLU-000008,0.605524,0.596912,6.58,0.417093
14,DFL-OBJ-0002DR,DFL-CLU-00000G,0.137905,0.580735,2.81,0.506937
15,DFL-OBJ-J01BGM,DFL-CLU-000008,0.392190,0.461912,6.13,0.523597
16,DFL-OBJ-J017RE,DFL-CLU-00000G,0.282476,0.443529,5.42,0.563621
17,DFL-OBJ-0027G6,DFL-CLU-00000G,0.517048,0.417059,0.28,0.569927
18,DFL-OBJ-0002HE,DFL-CLU-000008,0.854286,0.570441,4.44,0.579579
19,DFL-OBJ-0002BO,DFL-CLU-000008,0.598286,0.266324,6.41,0.732154
20,DFL-OBJ-J01APO,DFL-CLU-00000G,0.377143,0.198088,8.87,0.787650
21,DFL-OBJ-0026PM,DFL-CLU-00000G,0.610762,0.082794,3.92,0.914658

Jumlah pemain tim yang kehilangan bola: 11

,player_id,team_id,x,y,speed,distance_to_ball
1,DFL-OBJ-0002AU,DFL-CLU-00000G,0.443048,0.992941,8.73,0.010976
3,DFL-OBJ-0000IA,DFL-CLU-00000G,0.542095,0.883382,4.87,0.137564
5,DFL-OBJ-0027G0,DFL-CLU-00000G,0.416571,0.837206,7.75,0.148561
7,DFL-OBJ-0027KL,DFL-CLU-00000G,0.286952,0.910294,9.15,0.175512
11,DFL-OBJ-J01B8N,DFL-CLU-00000G,0.454667,0.622941,4.06,0.359791
12,DFL-OBJ-0002F5,DFL-CLU-00000G,0.324000,0.633382,5.78,0.370243
14,DFL-OBJ-0002DR,DFL-CLU-00000G,0.137905,0.580735,2.81,0.506937
16,DFL-OBJ-J017RE,DFL-CLU-00000G,0.282476,0.443529,5.42,0.563621
17,DFL-OBJ-0027G6,DFL-CLU-00000G,0.517048,0.417059,0.28,0.569927
20,DFL-OBJ-J01APO,DFL-CLU-00000G,0.377143,0.198088,8.87,0.787650
21,DFL-OBJ-0026PM,DFL-CLU-00000G,0.610762,0.082794,3.92,0.914658

In [65]:
display(
    losing_players[
        [
            "player_id",
            "team_id",
            "x",
            "y",
            "speed",
            "distance_to_ball"
        ]
    ]
)

,player_id,team_id,x,y,speed,distance_to_ball
1,DFL-OBJ-0002AU,DFL-CLU-00000G,0.443048,0.992941,8.73,0.010976
3,DFL-OBJ-0000IA,DFL-CLU-00000G,0.542095,0.883382,4.87,0.137564
5,DFL-OBJ-0027G0,DFL-CLU-00000G,0.416571,0.837206,7.75,0.148561
7,DFL-OBJ-0027KL,DFL-CLU-00000G,0.286952,0.910294,9.15,0.175512
11,DFL-OBJ-J01B8N,DFL-CLU-00000G,0.454667,0.622941,4.06,0.359791
12,DFL-OBJ-0002F5,DFL-CLU-00000G,0.324000,0.633382,5.78,0.370243
14,DFL-OBJ-0002DR,DFL-CLU-00000G,0.137905,0.580735,2.81,0.506937
16,DFL-OBJ-J017RE,DFL-CLU-00000G,0.282476,0.443529,5.42,0.563621
17,DFL-OBJ-0027G6,DFL-CLU-00000G,0.517048,0.417059,0.28,0.569927
20,DFL-OBJ-J01APO,DFL-CLU-00000G,0.377143,0.198088,8.87,0.787650
21,DFL-OBJ-0026PM,DFL-CLU-00000G,0.610762,0.082794,3.92,0.914658

In [66]:
# ==========================================
# TIME SERIES JARAK PEMAIN KE BOLA
# SELAMA LOSS -> REGAIN
# ==========================================

losing_team = episode["losing_team"]

# Ambil semua player ID yang terpetakan ke team
losing_player_ids = (
    player_team_episode[
        player_team_episode["team_id"] == losing_team
    ]["player_id"]
    .dropna()
    .unique()
    .tolist()
)

print("Jumlah pemain losing team:", len(losing_player_ids))

distance_records = []

# Tracking dari loss sampai regain
episode_frames = episode_tracking[
    (episode_tracking["period_id"] == period_id)
    & (episode_tracking["timestamp"] >= t0)
    & (episode_tracking["timestamp"] <= t1)
].copy()

for _, frame in episode_frames.iterrows():

    timestamp = frame["timestamp"]

    ball_x = frame["ball_x"]
    ball_y = frame["ball_y"]

    relative_time = (
        timestamp - t0
    ).total_seconds()

    for player_id in losing_player_ids:

        x_col = f"{player_id}_x"
        y_col = f"{player_id}_y"
        s_col = f"{player_id}_s"

        if (
            x_col not in episode_tracking.columns
            or y_col not in episode_tracking.columns
        ):
            continue

        x = frame[x_col]
        y = frame[y_col]

        if pd.isna(x) or pd.isna(y):
            continue

        distance = (
            (
                (x - ball_x) ** 2
                +
                (y - ball_y) ** 2
            ) ** 0.5
        )

        speed = frame[s_col]

        distance_records.append({
            "timestamp": timestamp,
            "relative_time": relative_time,
            "frame_id": frame["frame_id"],
            "player_id": player_id,
            "distance_to_ball": distance,
            "speed": speed
        })

distance_ts = pd.DataFrame(distance_records)

print(
    "Jumlah record:",
    len(distance_ts)
)

display(distance_ts.head(30))

# ==========================================
# PERUBAHAN JARAK TERHADAP SAAT LOSS
# ==========================================

initial_distance = (
    distance_ts
    .groupby("player_id")["distance_to_ball"]
    .transform("first")
)

distance_ts["distance_change"] = (
    distance_ts["distance_to_ball"]
    - initial_distance
)

display(
    distance_ts.head(30)
)

# ==========================================
# PERUBAHAN JARAK DARI LOSS -> REGAIN
# ==========================================

player_response = (
    distance_ts
    .sort_values(
        ["player_id", "timestamp"]
    )
    .groupby("player_id")
    .agg(
        initial_distance=(
            "distance_to_ball",
            "first"
        ),
        final_distance=(
            "distance_to_ball",
            "last"
        ),
        min_distance=(
            "distance_to_ball",
            "min"
        ),
        initial_speed=(
            "speed",
            "first"
        ),
        max_speed=(
            "speed",
            "max"
        )
    )
    .reset_index()
)

player_response["distance_change"] = (
    player_response["final_distance"]
    - player_response["initial_distance"]
)

player_response["distance_reduction"] = (
    player_response["initial_distance"]
    - player_response["min_distance"]
)

player_response = player_response.sort_values(
    "distance_reduction",
    ascending=False
)

display(player_response)

# ==========================================
# FITUR KOLEKTIF LOSING TEAM
# ==========================================

team_pressure_ts = (
    distance_ts
    .groupby(
        ["timestamp", "relative_time", "frame_id"]
    )
    .agg(
        nearest_player_distance=(
            "distance_to_ball",
            "min"
        ),
        mean_player_distance=(
            "distance_to_ball",
            "mean"
        ),
        players_count=(
            "player_id",
            "nunique"
        )
    )
    .reset_index()
)

display(team_pressure_ts.head(30))

Jumlah pemain losing team: 16
Jumlah record: 913

,timestamp,relative_time,frame_id,player_id,distance_to_ball,speed
0,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0027G6,0.569927,0.28
1,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0027KL,0.175512,9.15
2,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-J01B8N,0.359791,4.06
3,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0002AU,0.010976,8.73
4,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0027G0,0.148561,7.75
5,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-J017RE,0.563621,5.42
6,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0026PM,0.914658,3.92
7,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0002DR,0.506937,2.81
8,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0002F5,0.370243,5.78
9,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-J01APO,0.787650,8.87
10,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0000IA,0.137564,4.87
11,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0027G6,0.569032,0.34
12,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0027KL,0.176739,9.06
13,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-J01B8N,0.358720,4.06
14,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0002AU,0.012425,9.42
15,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0027G0,0.147343,7.61
16,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-J017RE,0.563140,5.37
17,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0026PM,0.913043,3.97
18,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0002DR,0.507520,2.71
19,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0002F5,0.369730,5.80
20,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-J01APO,0.785685,8.89
21,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0000IA,0.134784,4.66
22,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0027G6,0.572025,0.43
23,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0027KL,0.181549,8.97
24,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-J01B8N,0.362209,4.06
25,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0002AU,0.011798,10.14
26,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0027G0,0.150751,7.49
27,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-J017RE,0.567533,5.34
28,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0026PM,0.915160,4.00
29,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0002DR,0.512881,2.62

,timestamp,relative_time,frame_id,player_id,distance_to_ball,speed,distance_change
0,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0027G6,0.569927,0.28,0.000000
1,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0027KL,0.175512,9.15,0.000000
2,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-J01B8N,0.359791,4.06,0.000000
3,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0002AU,0.010976,8.73,0.000000
4,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0027G0,0.148561,7.75,0.000000
5,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-J017RE,0.563621,5.42,0.000000
6,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0026PM,0.914658,3.92,0.000000
7,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0002DR,0.506937,2.81,0.000000
8,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0002F5,0.370243,5.78,0.000000
9,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-J01APO,0.787650,8.87,0.000000
10,0 days 00:01:22.040000,0.00,12051,DFL-OBJ-0000IA,0.137564,4.87,0.000000
11,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0027G6,0.569032,0.34,-0.000895
12,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0027KL,0.176739,9.06,0.001227
13,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-J01B8N,0.358720,4.06,-0.001070
14,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0002AU,0.012425,9.42,0.001449
15,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0027G0,0.147343,7.61,-0.001218
16,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-J017RE,0.563140,5.37,-0.000481
17,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0026PM,0.913043,3.97,-0.001615
18,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0002DR,0.507520,2.71,0.000583
19,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0002F5,0.369730,5.80,-0.000513
20,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-J01APO,0.785685,8.89,-0.001965
21,0 days 00:01:22.080000,0.04,12052,DFL-OBJ-0000IA,0.134784,4.66,-0.002779
22,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0027G6,0.572025,0.43,0.002098
23,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0027KL,0.181549,8.97,0.006037
24,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-J01B8N,0.362209,4.06,0.002418
25,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0002AU,0.011798,10.14,0.000822
26,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0027G0,0.150751,7.49,0.002191
27,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-J017RE,0.567533,5.34,0.003911
28,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0026PM,0.915160,4.00,0.000502
29,0 days 00:01:22.120000,0.08,12053,DFL-OBJ-0002DR,0.512881,2.62,0.005944

,player_id,initial_distance,final_distance,min_distance,initial_speed,max_speed,distance_change,distance_reduction
7,DFL-OBJ-0027KL,0.175512,0.008537,0.008537,9.15,12.99,-0.166975,0.166975
9,DFL-OBJ-J01APO,0.787650,0.662204,0.661956,8.87,9.79,-0.125447,0.125694
3,DFL-OBJ-0002F5,0.370243,0.282505,0.282083,5.78,10.80,-0.087737,0.088160
2,DFL-OBJ-0002DR,0.506937,0.426528,0.426528,2.81,12.12,-0.080408,0.080408
8,DFL-OBJ-J017RE,0.563621,0.496359,0.495829,5.42,7.65,-0.067262,0.067792
5,DFL-OBJ-0027G0,0.148561,0.110148,0.089714,7.75,7.75,-0.038413,0.058847
4,DFL-OBJ-0026PM,0.914658,0.870179,0.864050,3.92,10.44,-0.044480,0.050609
0,DFL-OBJ-0000IA,0.137564,0.273135,0.100110,4.87,13.41,0.135571,0.037454
6,DFL-OBJ-0027G6,0.569927,0.553061,0.537253,0.28,13.67,-0.016866,0.032674
10,DFL-OBJ-J01B8N,0.359791,0.367204,0.347054,4.06,5.47,0.007413,0.012736
1,DFL-OBJ-0002AU,0.010976,0.264723,0.010976,8.73,24.07,0.253746,0.000000

,timestamp,relative_time,frame_id,nearest_player_distance,mean_player_distance,players_count
0,0 days 00:01:22.040000,0.00,12051,0.010976,0.413222,11
1,0 days 00:01:22.080000,0.04,12052,0.012425,0.412560,11
2,0 days 00:01:22.120000,0.08,12053,0.011798,0.415477,11
3,0 days 00:01:22.160000,0.12,12054,0.013070,0.415453,11
4,0 days 00:01:22.200000,0.16,12055,0.014554,0.415348,11
5,0 days 00:01:22.240000,0.20,12056,0.016068,0.415118,11
6,0 days 00:01:22.280000,0.24,12057,0.017274,0.415058,11
7,0 days 00:01:22.320000,0.28,12058,0.018645,0.414939,11
8,0 days 00:01:22.360000,0.32,12059,0.020003,0.414487,11
9,0 days 00:01:22.400000,0.36,12060,0.020758,0.414669,11
10,0 days 00:01:22.440000,0.40,12061,0.021876,0.414316,11
11,0 days 00:01:22.480000,0.44,12062,0.022783,0.414239,11
12,0 days 00:01:22.520000,0.48,12063,0.023542,0.414134,11
13,0 days 00:01:22.560000,0.52,12064,0.024289,0.413924,11
14,0 days 00:01:22.600000,0.56,12065,0.024525,0.413590,11
15,0 days 00:01:22.640000,0.60,12066,0.024673,0.413702,11
16,0 days 00:01:22.680000,0.64,12067,0.024558,0.412621,11
17,0 days 00:01:22.720000,0.68,12068,0.024180,0.412962,11
18,0 days 00:01:22.760000,0.72,12069,0.023923,0.412510,11
19,0 days 00:01:22.800000,0.76,12070,0.023495,0.412071,11
20,0 days 00:01:22.840000,0.80,12071,0.023089,0.411639,11
21,0 days 00:01:22.880000,0.84,12072,0.022466,0.411359,11
22,0 days 00:01:22.920000,0.88,12073,0.022039,0.410961,11
23,0 days 00:01:22.960000,0.92,12074,0.021633,0.410454,11
24,0 days 00:01:23,0.96,12075,0.021246,0.409660,11
25,0 days 00:01:23.040000,1.00,12076,0.020688,0.409404,11
26,0 days 00:01:23.080000,1.04,12077,0.020104,0.408951,11
27,0 days 00:01:23.120000,1.08,12078,0.019628,0.408740,11
28,0 days 00:01:23.160000,1.12,12079,0.019192,0.408038,11
29,0 days 00:01:23.200000,1.16,12080,0.017829,0.407738,11